package com.ihappy.role.infrastructure.repo.mybatis.mapper.company;

import com.ihappy.company.domain.bo.GetCompanyRoleFuncMenuBO;
import com.ihappy.role.domain.bo.CheckRoleNameBO;
import com.ihappy.role.domain.bo.CompanyRoleBO;
import com.ihappy.role.domain.bo.QueryCompanyRolePageBO;
import com.ihappy.role.domain.dbdo.company.BaseinfoCompanyRole;

import java.util.List;
import java.util.Map;

public interface BaseinfoCompanyRoleMapper {
    /**
     * 根据角色id数组查询角色列表
     * @param roleIdList
     * @return
     */
    List<BaseinfoCompanyRole> selectByPrimaryKeyList(List<Long> roleIdList);

    /**
     * 根据公司id数组查询角色列表
     * @param compIdList
     * @return
     */
    List<BaseinfoCompanyRole> selectByCompIdList(List<Long> compIdList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_role_0
     *
     * @mbg.generated Sat Mar 31 16:16:26 CST 2018
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_role_0
     *
     * @mbg.generated Sat Mar 31 16:16:26 CST 2018
     */
    int insert(BaseinfoCompanyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_role_0
     *
     * @mbg.generated Sat Mar 31 16:16:26 CST 2018
     */
    int insertSelective(BaseinfoCompanyRole record);

    /**
     * 添加公司角色
     * @param baseinfoCompanyRole
     * @return
     */
    int insertCompanyRole(BaseinfoCompanyRole baseinfoCompanyRole);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_role_0
     *
     * @mbg.generated Sat Mar 31 16:16:26 CST 2018
     */
    BaseinfoCompanyRole selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_role_0
     *
     * @mbg.generated Sat Mar 31 16:16:26 CST 2018
     */
    int updateByPrimaryKeySelective(BaseinfoCompanyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_role_0
     *
     * @mbg.generated Sat Mar 31 16:16:26 CST 2018
     */
    int updateByPrimaryKey(BaseinfoCompanyRole record);

    /**
     * 根据公司id查询角色信息
     * @param queryCompanyRolePageBO
     * @return
     */
    List<BaseinfoCompanyRole> selectRolePageByCompId(QueryCompanyRolePageBO queryCompanyRolePageBO);

    /**
     * 根据公司id和角色id查询角色信息
     * @param map
     * @return
     */
    BaseinfoCompanyRole selectOneRoleByCompIdAndRoleId(Map<Integer,Integer> map);

    /**
     * 查看角色名称是否重复
     * @param checkRoleNameBO
     * @return
     */
    BaseinfoCompanyRole checkRoleNameIsExist(CheckRoleNameBO checkRoleNameBO);

    /**
     * 查看角色编号是否重复
     * @param companyRoleBO
     * @return
     */
    BaseinfoCompanyRole checkCompanyRoleNoIsOrNotRepeat(CompanyRoleBO companyRoleBO);

    /**
     * 根据角色ID和角色权限查询获取的功能菜单
     * @param getCompanyRoleFuncMenuBO
     * @return
     */
    BaseinfoCompanyRole selectCompanyRoleByRoleId(GetCompanyRoleFuncMenuBO getCompanyRoleFuncMenuBO);

    /**
     * 根据角色id修改角色信息
     * @param companyRoleBO
     * @return
     */
    int updateOneRoleInfoByRoleId(CompanyRoleBO companyRoleBO);

    /**
     * 根据角色id删除角色信息
     * @param companyRoleBO
     * @return
     */
    int deleteCompanyRoleByRoleId(CompanyRoleBO companyRoleBO);
    /**
     * 根据权限查询不同的角色列表
     * @param queryCompanyRolePageBO
     * @return
     */
    List<BaseinfoCompanyRole> selectCompRoleByCondition(QueryCompanyRolePageBO queryCompanyRolePageBO);

}