package com.ihappy.stock.domain.dbdo;

public class BaseinfoCompanyStock {
    /**
     * 是否默认仓库  0：否   1：是
     */
    private Integer isDefault;
    private Long inventorying;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.stock_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Long stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.stock_no
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private String stockNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.stock_name
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private String stockName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.stock_acreage
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Integer stockAcreage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.area_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.province
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.city
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.zone
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private String zone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.address
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.stock_tel
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private String stockTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.stock_linkman
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private String stockLinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.comp_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Integer compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.store_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Long storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.sort
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.created_at
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.updated_at
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.created_person_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.updated_person_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.is_deleted
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.forbidden
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Integer forbidden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.is_public
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private Integer isPublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_stock.stock_memo
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    private String stockMemo;
    /**
     * 门店名称
     */
    private String storeName;

    public String getStoreName() {
        return storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    public Integer getIsDefault() {
        return isDefault;
    }

    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    public Long getInventorying() {
        return inventorying;
    }

    public void setInventorying(Long inventorying) {
        this.inventorying = inventorying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.stock_id
     *
     * @return the value of baseinfo_company_stock.stock_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Long getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.stock_id
     *
     * @param stockId the value for baseinfo_company_stock.stock_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setStockId(Long stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.stock_no
     *
     * @return the value of baseinfo_company_stock.stock_no
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public String getStockNo() {
        return stockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.stock_no
     *
     * @param stockNo the value for baseinfo_company_stock.stock_no
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setStockNo(String stockNo) {
        this.stockNo = stockNo == null ? null : stockNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.stock_name
     *
     * @return the value of baseinfo_company_stock.stock_name
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.stock_name
     *
     * @param stockName the value for baseinfo_company_stock.stock_name
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.stock_acreage
     *
     * @return the value of baseinfo_company_stock.stock_acreage
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Integer getStockAcreage() {
        return stockAcreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.stock_acreage
     *
     * @param stockAcreage the value for baseinfo_company_stock.stock_acreage
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setStockAcreage(Integer stockAcreage) {
        this.stockAcreage = stockAcreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.area_id
     *
     * @return the value of baseinfo_company_stock.area_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.area_id
     *
     * @param areaId the value for baseinfo_company_stock.area_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.province
     *
     * @return the value of baseinfo_company_stock.province
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.province
     *
     * @param province the value for baseinfo_company_stock.province
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.city
     *
     * @return the value of baseinfo_company_stock.city
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.city
     *
     * @param city the value for baseinfo_company_stock.city
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.zone
     *
     * @return the value of baseinfo_company_stock.zone
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.zone
     *
     * @param zone the value for baseinfo_company_stock.zone
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setZone(String zone) {
        this.zone = zone == null ? null : zone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.address
     *
     * @return the value of baseinfo_company_stock.address
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.address
     *
     * @param address the value for baseinfo_company_stock.address
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.stock_tel
     *
     * @return the value of baseinfo_company_stock.stock_tel
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public String getStockTel() {
        return stockTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.stock_tel
     *
     * @param stockTel the value for baseinfo_company_stock.stock_tel
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setStockTel(String stockTel) {
        this.stockTel = stockTel == null ? null : stockTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.stock_linkman
     *
     * @return the value of baseinfo_company_stock.stock_linkman
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public String getStockLinkman() {
        return stockLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.stock_linkman
     *
     * @param stockLinkman the value for baseinfo_company_stock.stock_linkman
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setStockLinkman(String stockLinkman) {
        this.stockLinkman = stockLinkman == null ? null : stockLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.comp_id
     *
     * @return the value of baseinfo_company_stock.comp_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.comp_id
     *
     * @param compId the value for baseinfo_company_stock.comp_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.store_id
     *
     * @return the value of baseinfo_company_stock.store_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.store_id
     *
     * @param storeId the value for baseinfo_company_stock.store_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.sort
     *
     * @return the value of baseinfo_company_stock.sort
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.sort
     *
     * @param sort the value for baseinfo_company_stock.sort
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.created_at
     *
     * @return the value of baseinfo_company_stock.created_at
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.created_at
     *
     * @param createdAt the value for baseinfo_company_stock.created_at
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.updated_at
     *
     * @return the value of baseinfo_company_stock.updated_at
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.updated_at
     *
     * @param updatedAt the value for baseinfo_company_stock.updated_at
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.created_person_id
     *
     * @return the value of baseinfo_company_stock.created_person_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.created_person_id
     *
     * @param createdPersonId the value for baseinfo_company_stock.created_person_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.updated_person_id
     *
     * @return the value of baseinfo_company_stock.updated_person_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.updated_person_id
     *
     * @param updatedPersonId the value for baseinfo_company_stock.updated_person_id
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.is_deleted
     *
     * @return the value of baseinfo_company_stock.is_deleted
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.is_deleted
     *
     * @param isDeleted the value for baseinfo_company_stock.is_deleted
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.forbidden
     *
     * @return the value of baseinfo_company_stock.forbidden
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Integer getForbidden() {
        return forbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.forbidden
     *
     * @param forbidden the value for baseinfo_company_stock.forbidden
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setForbidden(Integer forbidden) {
        this.forbidden = forbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.is_public
     *
     * @return the value of baseinfo_company_stock.is_public
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public Integer getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.is_public
     *
     * @param isPublic the value for baseinfo_company_stock.is_public
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setIsPublic(Integer isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_stock.stock_memo
     *
     * @return the value of baseinfo_company_stock.stock_memo
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public String getStockMemo() {
        return stockMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_stock.stock_memo
     *
     * @param stockMemo the value for baseinfo_company_stock.stock_memo
     *
     * @mbg.generated Fri Apr 13 09:19:04 CST 2018
     */
    public void setStockMemo(String stockMemo) {
        this.stockMemo = stockMemo == null ? null : stockMemo.trim();
    }
}