package com.ihappy.company.infrastructure.repo.mybatis.mapper.comp;

import com.ihappy.company.domain.dbdo.BaseinfoCompanyPrintConfig;

import java.util.List;

public interface BaseinfoCompanyPrintConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_print_config
     *
     * @mbg.generated Fri Jun 01 14:33:11 CST 2018
     */
    int deleteByPrimaryKey(Integer configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_print_config
     *
     * @mbg.generated Fri Jun 01 14:33:11 CST 2018
     */
    int insert(BaseinfoCompanyPrintConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_print_config
     *
     * @mbg.generated Fri Jun 01 14:33:11 CST 2018
     */
    int insertSelective(BaseinfoCompanyPrintConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_print_config
     *
     * @mbg.generated Fri Jun 01 14:33:11 CST 2018
     */
    BaseinfoCompanyPrintConfig selectByPrimaryKey(Integer configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_print_config
     *
     * @mbg.generated Fri Jun 01 14:33:11 CST 2018
     */
    int updateByPrimaryKeySelective(BaseinfoCompanyPrintConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_print_config
     *
     * @mbg.generated Fri Jun 01 14:33:11 CST 2018
     */
    int updateByPrimaryKey(BaseinfoCompanyPrintConfig record);

     /**
       * @Description: 根据条件查询打印配置信息
       * @Param:
       * @return:
       * @Author: zhangtengpo 
       * @Date: 2018/6/1
       */
    List<BaseinfoCompanyPrintConfig> selectSelective(BaseinfoCompanyPrintConfig baseinfoCompanyPrintConfig);


}