package com.ihappy.company.infrastructure.repo.mybatis.mapper.comp;

import com.ihappy.company.domain.dbdo.BaseinfoCompanyBrand;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface BaseinfoCompanyBrandMapper {
    /**
     * 根据公司id和其他条件查询品牌列表
     * @param map
     * @return
     */
    List<BaseinfoCompanyBrand> selectCompanyBrandListByCompIdAndCondition(Map<String,Object> map);

    /**
     * 根据公司id查询品牌列表
     * @param compId
     * @return
     */
    List<BaseinfoCompanyBrand> selectListByCompId(Integer compId);

    /**
     * 根据brand_id删除
     * @param baseinfoCompanyBrand
     * @return
     */
    int updateDeletedByBrandId(BaseinfoCompanyBrand baseinfoCompanyBrand);

    /**
     * 根据brand_ids删除
     * @param obj
     * @param ids
     * @return
     */
    int updateDeletedByBrandIds(@Param("obj") BaseinfoCompanyBrand obj,@Param("ids") List<Integer> ids);

    /**
     * 根据品牌名称查询列表
     * @param baseinfoCompanyBrand
     * @return
     */
    List<BaseinfoCompanyBrand> selectByBrandName(BaseinfoCompanyBrand baseinfoCompanyBrand);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_brand
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    int deleteByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_brand
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    int insert(BaseinfoCompanyBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_brand
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    int insertSelective(BaseinfoCompanyBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_brand
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    BaseinfoCompanyBrand selectByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_brand
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    int updateByPrimaryKeySelective(BaseinfoCompanyBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_brand
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(BaseinfoCompanyBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_brand
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    int updateByPrimaryKey(BaseinfoCompanyBrand record);
}