package com.ihappy.company.infrastructure.repo.mybatis.mapper.comp;

import com.ihappy.company.domain.dbdo.BaseinfoCompanyVerifiedHistory;

public interface BaseinfoCompanyVerifiedHistoryMapper {
    /**
     * 根据条件查询 单个
     * @param condition
     * @return
     */
    BaseinfoCompanyVerifiedHistory selectOneByCondition(BaseinfoCompanyVerifiedHistory condition);

    /**
     * 根据条件查询
     * @param condition
     * @return
     */
    BaseinfoCompanyVerifiedHistory selectByCondition(BaseinfoCompanyVerifiedHistory condition);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_verified_history
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    int deleteByPrimaryKey(Integer verifiedHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_verified_history
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    int insert(BaseinfoCompanyVerifiedHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_verified_history
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    int insertSelective(BaseinfoCompanyVerifiedHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_verified_history
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    BaseinfoCompanyVerifiedHistory selectByPrimaryKey(Integer verifiedHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_verified_history
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    int updateByPrimaryKeySelective(BaseinfoCompanyVerifiedHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_verified_history
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    int updateByPrimaryKey(BaseinfoCompanyVerifiedHistory record);
}