package com.ihappy.company.infrastructure.repo.mybatis.mapper.comp;

import com.ihappy.company.domain.dbdo.BaseinfoCompanyExtendServiceJournal;

public interface BaseinfoCompanyExtendServiceJournalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_extend_service_journal
     *
     * @mbg.generated Thu Jun 28 14:04:31 CST 2018
     */
    int deleteByPrimaryKey(Long journalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_extend_service_journal
     *
     * @mbg.generated Thu Jun 28 14:04:31 CST 2018
     */
    int insert(BaseinfoCompanyExtendServiceJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_extend_service_journal
     *
     * @mbg.generated Thu Jun 28 14:04:31 CST 2018
     */
    int insertSelective(BaseinfoCompanyExtendServiceJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_extend_service_journal
     *
     * @mbg.generated Thu Jun 28 14:04:31 CST 2018
     */
    BaseinfoCompanyExtendServiceJournal selectByPrimaryKey(Long journalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_extend_service_journal
     *
     * @mbg.generated Thu Jun 28 14:04:31 CST 2018
     */
    int updateByPrimaryKeySelective(BaseinfoCompanyExtendServiceJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_extend_service_journal
     *
     * @mbg.generated Thu Jun 28 14:04:31 CST 2018
     */
    int updateByPrimaryKey(BaseinfoCompanyExtendServiceJournal record);
}