package com.ihappy.company.infrastructure.repo.mybatis.mapper.comp;

import com.ihappy.company.domain.dbdo.CommonParam;

/**
 * Created by sunjd on 2018/4/3.
 */
public interface CommonParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_param
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_param
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    int insert(CommonParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_param
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    int insertSelective(CommonParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_param
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    CommonParam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_param
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    int updateByPrimaryKeySelective(CommonParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_param
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    int updateByPrimaryKey(CommonParam record);

    Long getValueByName(String name);
}
