package com.ihappy.company.infrastructure.repo.mybatis.mapper.comp;

import com.ihappy.company.domain.bo.*;
import com.ihappy.company.domain.dbdo.OrderCompanyJournal;

import java.util.List;

public interface OrderCompanyJournalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_company_journal
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    int insert(OrderCompanyJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_company_journal
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    int insertSelective(OrderCompanyJournal record);


    /**
     * 分页查询用户信息
     * @param orderCompanyJournalPageQueryBO
     * @return
     */
    List<OrderCompanyJournal> getOrderCompanyJournalList(OrderCompanyJournalPageQueryBO orderCompanyJournalPageQueryBO);

    /**
     * 分页统计
     * @param orderCompanyJournalPageQueryBO
     * @return
     */
    int getOrderCompanyJournalCount(OrderCompanyJournalPageQueryBO orderCompanyJournalPageQueryBO);

    /**
     * 查看详情
     * @param orderCompanyJournalByIdBO
     * @return
     */
    OrderCompanyJournal getOrderCompanyJournalDetailById(OrderCompanyJournalByIdBO orderCompanyJournalByIdBO);

    /**
     * 修改信息
     * @param updateOrderCompanyJournalBO
     * @return
     */
    int updateOrderCompanyJournalById(UpdateOrderCompanyJournalBO updateOrderCompanyJournalBO);

    /**
     * 作废单据
     * @param cancelOrderCompanyJournalBO
     * @return
     */
    int cancelOrderCompanyJournalById(CancelOrderCompanyJournalBO cancelOrderCompanyJournalBO);

    /**
     * 查询公司小的缴费记录
     * @param orderCompanyJournalByCompIdBO
     * @return
     */
    List<OrderCompanyJournal> getOrderCompanyJournalDetailByCompId(OrderCompanyJournalByCompIdBO orderCompanyJournalByCompIdBO);
}