package com.ihappy.store.domain.dbdo.store;

public class BaseinfoCompanyStoreCt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.store_ct_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private Long storeCtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.comp_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private Integer compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.store_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.ct_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private Integer ctId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.ct_name
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private String ctName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.start_time
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private Long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.end_time
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.comment
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.created_at
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.updated_at
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.created_person_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.updated_person_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store_ct_0.is_deleted
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.store_ct_id
     *
     * @return the value of baseinfo_company_store_ct_0.store_ct_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public Long getStoreCtId() {
        return storeCtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.store_ct_id
     *
     * @param storeCtId the value for baseinfo_company_store_ct_0.store_ct_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setStoreCtId(Long storeCtId) {
        this.storeCtId = storeCtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.comp_id
     *
     * @return the value of baseinfo_company_store_ct_0.comp_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.comp_id
     *
     * @param compId the value for baseinfo_company_store_ct_0.comp_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.store_id
     *
     * @return the value of baseinfo_company_store_ct_0.store_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.store_id
     *
     * @param storeId the value for baseinfo_company_store_ct_0.store_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.ct_id
     *
     * @return the value of baseinfo_company_store_ct_0.ct_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public Integer getCtId() {
        return ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.ct_id
     *
     * @param ctId the value for baseinfo_company_store_ct_0.ct_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setCtId(Integer ctId) {
        this.ctId = ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.ct_name
     *
     * @return the value of baseinfo_company_store_ct_0.ct_name
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public String getCtName() {
        return ctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.ct_name
     *
     * @param ctName the value for baseinfo_company_store_ct_0.ct_name
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setCtName(String ctName) {
        this.ctName = ctName == null ? null : ctName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.start_time
     *
     * @return the value of baseinfo_company_store_ct_0.start_time
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.start_time
     *
     * @param startTime the value for baseinfo_company_store_ct_0.start_time
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.end_time
     *
     * @return the value of baseinfo_company_store_ct_0.end_time
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.end_time
     *
     * @param endTime the value for baseinfo_company_store_ct_0.end_time
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.comment
     *
     * @return the value of baseinfo_company_store_ct_0.comment
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.comment
     *
     * @param comment the value for baseinfo_company_store_ct_0.comment
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.created_at
     *
     * @return the value of baseinfo_company_store_ct_0.created_at
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.created_at
     *
     * @param createdAt the value for baseinfo_company_store_ct_0.created_at
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.updated_at
     *
     * @return the value of baseinfo_company_store_ct_0.updated_at
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.updated_at
     *
     * @param updatedAt the value for baseinfo_company_store_ct_0.updated_at
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.created_person_id
     *
     * @return the value of baseinfo_company_store_ct_0.created_person_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.created_person_id
     *
     * @param createdPersonId the value for baseinfo_company_store_ct_0.created_person_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.updated_person_id
     *
     * @return the value of baseinfo_company_store_ct_0.updated_person_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.updated_person_id
     *
     * @param updatedPersonId the value for baseinfo_company_store_ct_0.updated_person_id
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store_ct_0.is_deleted
     *
     * @return the value of baseinfo_company_store_ct_0.is_deleted
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store_ct_0.is_deleted
     *
     * @param isDeleted the value for baseinfo_company_store_ct_0.is_deleted
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}