package com.ihappy.store.domain.dbdo.store;

public class BaseinfoCompanyStore {
    private Integer version;

    /**
     * 0:体验;1:付费
     */
    private Integer expireStatus;
    /**
     * '过期时间
     */
    private Long expireDate;
    /**
     * 付款备注
     */
    private String payRemark;
    /**
     * 备注者姓名
     */
    private String payRemarkUserName;
    /**
     * 备注者id
     */
    private Long payRemarkUserId;
    /**
     * 备注时间
     */
    private Long payRemarkTime;
    /**
     * 门店名称模糊查询
     */
    private String storeNameSearch;
    /**
     * 是否公共门店（总店） 0：不是  1：是
     */
    private Integer isPublic;

    /**
     * 扩展属性
     */
    private String attributes;
    /**
     * 是否默认门店   0：否   1：是
     */
    private Integer isDefault;
    /**
     * 门店id
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.store_no
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String storeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.store_name
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.store_region_id
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer storeRegionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.store_region_name
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String storeRegionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.area_id
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.province
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.city
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.zone
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String zone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.address
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.store_acreage
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer storeAcreage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.zip
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.store_phone
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String storePhone;
    private String storeTel;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.store_contact
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String storeContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.store_type
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer storeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.is_valid
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.create_time
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.close_time
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.business_hours
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String businessHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.online
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer online;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.location
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.logo_url
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.comp_id
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.admin_person_id
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Long adminPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.status
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.manage_pattern
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer managePattern;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.channel_type
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer channelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.sort
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.description
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.Online_show_sales
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer onlineShowSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.Online_show_stocks
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer onlineShowStocks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.Online_Reduce_after_payed
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer onlineReduceAfterPayed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.created_at
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Long createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.updated_at
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Long updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.created_person_id
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Long createdPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to  the database column baseinfo_company_store.updated_person_id
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Long updatedPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_store.is_deleted
     *
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    private Integer isDeleted;

    /**
     * 微商铺名称
     */
    private String weshopName;
    /**
     * 微商铺logo
     */
    private String weshopLogoImages;
    /**
     * 微商铺管理人名称
     */
    private String weshopManagerName;
    /**
     * 微商铺管理人id
     */
    private Long weshopManagerId;
    /**
     * 微商铺联系方式
     */
    private String weshopContactType;
    /**
     * 微商铺主营商品分类
     */
    private String businessCategory;
    /**
     * 微商铺门头图片
     */
    private String weshopImages;
    /**
     * 微商铺公告
     */
    private String weshopNotice;
    /**
     * 为否开启微商铺公告
     */
    private Integer isOpenWeshopNotice;
    /**
     * 微商铺状态 0草稿，1发布, 2下线
     */
    private Integer weshopStatus;

    private Integer isDeletedWeshop;

    private String printIp;

    private String printPort;

    private Integer isHasWeshop;

    private String weshopProvince;

    private String weshopCity;

    private String weshopZone;

    private String weshopAddress;
    private Integer forbidden;
    private String alipayAccountName;
    private String alipayReceiptQrcode;
    private String alipayReceiptQrcodeContent;
    /**
     * 支付宝账号二维码
     */
    private String alipayAccountQrcode;
    /**
     * 支付宝账号二维码内容
     */
    private String alipayAccountQrcodeContent;
    private String wechatAccountName;
    private String wechatAccountQrcode;
    private String wechatAccountQrcodeContent;
    private String wechatReceiptQrcode;
    private String wechatReceiptQrcodeContent;
    
    public Long getExpireDate() {
        return expireDate;
    }

    public void setExpireDate(Long expireDate) {
        this.expireDate = expireDate;
    }

    public String getPayRemark() {
        return payRemark;
    }

    public void setPayRemark(String payRemark) {
        this.payRemark = payRemark;
    }

    public String getPayRemarkUserName() {
        return payRemarkUserName;
    }

    public void setPayRemarkUserName(String payRemarkUserName) {
        this.payRemarkUserName = payRemarkUserName;
    }

    public Long getPayRemarkUserId() {
        return payRemarkUserId;
    }

    public void setPayRemarkUserId(Long payRemarkUserId) {
        this.payRemarkUserId = payRemarkUserId;
    }

    public Long getPayRemarkTime() {
        return payRemarkTime;
    }

    public void setPayRemarkTime(Long payRemarkTime) {
        this.payRemarkTime = payRemarkTime;
    }

    public Integer getForbidden() {
        return forbidden;
    }

    public void setForbidden(Integer forbidden) {
        this.forbidden = forbidden;
    }

    public String getAlipayAccountName() {
        return alipayAccountName;
    }

    public void setAlipayAccountName(String alipayAccountName) {
        this.alipayAccountName = alipayAccountName;
    }

    public String getAlipayReceiptQrcode() {
        return alipayReceiptQrcode;
    }

    public void setAlipayReceiptQrcode(String alipayReceiptQrcode) {
        this.alipayReceiptQrcode = alipayReceiptQrcode;
    }

    public String getAlipayReceiptQrcodeContent() {
        return alipayReceiptQrcodeContent;
    }

    public void setAlipayReceiptQrcodeContent(String alipayReceiptQrcodeContent) {
        this.alipayReceiptQrcodeContent = alipayReceiptQrcodeContent;
    }

    public String getWechatAccountName() {
        return wechatAccountName;
    }

    public void setWechatAccountName(String wechatAccountName) {
        this.wechatAccountName = wechatAccountName;
    }

    public String getWechatAccountQrcode() {
        return wechatAccountQrcode;
    }

    public void setWechatAccountQrcode(String wechatAccountQrcode) {
        this.wechatAccountQrcode = wechatAccountQrcode;
    }

    public String getWechatAccountQrcodeContent() {
        return wechatAccountQrcodeContent;
    }

    public void setWechatAccountQrcodeContent(String wechatAccountQrcodeContent) {
        this.wechatAccountQrcodeContent = wechatAccountQrcodeContent;
    }

    public String getWechatReceiptQrcode() {
        return wechatReceiptQrcode;
    }

    public void setWechatReceiptQrcode(String wechatReceiptQrcode) {
        this.wechatReceiptQrcode = wechatReceiptQrcode;
    }

    public String getWechatReceiptQrcodeContent() {
        return wechatReceiptQrcodeContent;
    }

    public void setWechatReceiptQrcodeContent(String wechatReceiptQrcodeContent) {
        this.wechatReceiptQrcodeContent = wechatReceiptQrcodeContent;
    }

    public Integer getIsPublic() {
        return isPublic;
    }

    public void setIsPublic(Integer isPublic) {
        this.isPublic = isPublic;
    }

    public String getWeshopProvince() {
        return weshopProvince;
    }

    public void setWeshopProvince(String weshopProvince) {
        this.weshopProvince = weshopProvince;
    }

    public String getWeshopCity() {
        return weshopCity;
    }

    public void setWeshopCity(String weshopCity) {
        this.weshopCity = weshopCity;
    }

    public String getWeshopZone() {
        return weshopZone;
    }

    public void setWeshopZone(String weshopZone) {
        this.weshopZone = weshopZone;
    }

    public String getWeshopAddress() {
        return weshopAddress;
    }

    public void setWeshopAddress(String weshopAddress) {
        this.weshopAddress = weshopAddress;
    }

    public Integer getIsDefault() {
        return isDefault;
    }

    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.store_id
     *
     * @return the value of baseinfo_company_store.store_id
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.store_id
     *
     * @param storeId the value for baseinfo_company_store.store_id
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.store_no
     *
     * @return the value of baseinfo_company_store.store_no
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getStoreNo() {
        return storeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.store_no
     *
     * @param storeNo the value for baseinfo_company_store.store_no
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setStoreNo(String storeNo) {
        this.storeNo = storeNo == null ? null : storeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.store_name
     *
     * @return the value of baseinfo_company_store.store_name
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.store_name
     *
     * @param storeName the value for baseinfo_company_store.store_name
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.store_region_id
     *
     * @return the value of baseinfo_company_store.store_region_id
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getStoreRegionId() {
        return storeRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.store_region_id
     *
     * @param storeRegionId the value for baseinfo_company_store.store_region_id
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setStoreRegionId(Integer storeRegionId) {
        this.storeRegionId = storeRegionId;
    }

    public String getAttributes() {
        return attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.store_region_name
     *
     * @return the value of baseinfo_company_store.store_region_name
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getStoreRegionName() {
        return storeRegionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.store_region_name
     *
     * @param storeRegionName the value for baseinfo_company_store.store_region_name
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setStoreRegionName(String storeRegionName) {
        this.storeRegionName = storeRegionName == null ? null : storeRegionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.area_id
     *
     * @return the value of baseinfo_company_store.area_id
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.area_id
     *
     * @param areaId the value for baseinfo_company_store.area_id
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.province
     *
     * @return the value of baseinfo_company_store.province
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.province
     *
     * @param province the value for baseinfo_company_store.province
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.city
     *
     * @return the value of baseinfo_company_store.city
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.city
     *
     * @param city the value for baseinfo_company_store.city
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.zone
     *
     * @return the value of baseinfo_company_store.zone
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.zone
     *
     * @param zone the value for baseinfo_company_store.zone
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setZone(String zone) {
        this.zone = zone == null ? null : zone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.address
     *
     * @return the value of baseinfo_company_store.address
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.address
     *
     * @param address the value for baseinfo_company_store.address
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.store_acreage
     *
     * @return the value of baseinfo_company_store.store_acreage
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getStoreAcreage() {
        return storeAcreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.store_acreage
     *
     * @param storeAcreage the value for baseinfo_company_store.store_acreage
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setStoreAcreage(Integer storeAcreage) {
        this.storeAcreage = storeAcreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.zip
     *
     * @return the value of baseinfo_company_store.zip
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.zip
     *
     * @param zip the value for baseinfo_company_store.zip
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.store_phone
     *
     * @return the value of baseinfo_company_store.store_phone
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getStorePhone() {
        return storePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.store_phone
     *
     * @param storePhone the value for baseinfo_company_store.store_phone
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setStorePhone(String storePhone) {
        this.storePhone = storePhone == null ? null : storePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.store_contact
     *
     * @return the value of baseinfo_company_store.store_contact
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getStoreContact() {
        return storeContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.store_contact
     *
     * @param storeContact the value for baseinfo_company_store.store_contact
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setStoreContact(String storeContact) {
        this.storeContact = storeContact == null ? null : storeContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.store_type
     *
     * @return the value of baseinfo_company_store.store_type
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getStoreType() {
        return storeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.store_type
     *
     * @param storeType the value for baseinfo_company_store.store_type
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setStoreType(Integer storeType) {
        this.storeType = storeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.is_valid
     *
     * @return the value of baseinfo_company_store.is_valid
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.is_valid
     *
     * @param isValid the value for baseinfo_company_store.is_valid
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.create_time
     *
     * @return the value of baseinfo_company_store.create_time
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.create_time
     *
     * @param createTime the value for baseinfo_company_store.create_time
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.close_time
     *
     * @return the value of baseinfo_company_store.close_time
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.close_time
     *
     * @param closeTime the value for baseinfo_company_store.close_time
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setCloseTime(Integer closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.business_hours
     *
     * @return the value of baseinfo_company_store.business_hours
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getBusinessHours() {
        return businessHours;
    }

    //所在地区
    public String area;

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.business_hours
     *
     * @param businessHours the value for baseinfo_company_store.business_hours
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setBusinessHours(String businessHours) {
        this.businessHours = businessHours == null ? null : businessHours.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.online
     *
     * @return the value of baseinfo_company_store.online
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.online
     *
     * @param online the value for baseinfo_company_store.online
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setOnline(Integer online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.location
     *
     * @return the value of baseinfo_company_store.location
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.location
     *
     * @param location the value for baseinfo_company_store.location
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.logo_url
     *
     * @return the value of baseinfo_company_store.logo_url
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.logo_url
     *
     * @param logoUrl the value for baseinfo_company_store.logo_url
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.comp_id
     *
     * @return the value of baseinfo_company_store.comp_id
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.comp_id
     *
     * @param compId the value for baseinfo_company_store.comp_id
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.admin_person_id
     *
     * @return the value of baseinfo_company_store.admin_person_id
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Long getAdminPersonId() {
        return adminPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.admin_person_id
     *
     * @param adminPersonId the value for baseinfo_company_store.admin_person_id
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setAdminPersonId(Long adminPersonId) {
        this.adminPersonId = adminPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.status
     *
     * @return the value of baseinfo_company_store.status
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.status
     *
     * @param status the value for baseinfo_company_store.status
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.manage_pattern
     *
     * @return the value of baseinfo_company_store.manage_pattern
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getManagePattern() {
        return managePattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.manage_pattern
     *
     * @param managePattern the value for baseinfo_company_store.manage_pattern
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setManagePattern(Integer managePattern) {
        this.managePattern = managePattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.channel_type
     *
     * @return the value of baseinfo_company_store.channel_type
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.channel_type
     *
     * @param channelType the value for baseinfo_company_store.channel_type
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setChannelType(Integer channelType) {
        this.channelType = channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.sort
     *
     * @return the value of baseinfo_company_store.sort
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.sort
     *
     * @param sort the value for baseinfo_company_store.sort
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.description
     *
     * @return the value of baseinfo_company_store.description
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.description
     *
     * @param description the value for baseinfo_company_store.description
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.Online_show_sales
     *
     * @return the value of baseinfo_company_store.Online_show_sales
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getOnlineShowSales() {
        return onlineShowSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.Online_show_sales
     *
     * @param onlineShowSales the value for baseinfo_company_store.Online_show_sales
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setOnlineShowSales(Integer onlineShowSales) {
        this.onlineShowSales = onlineShowSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.Online_show_stocks
     *
     * @return the value of baseinfo_company_store.Online_show_stocks
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getOnlineShowStocks() {
        return onlineShowStocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.Online_show_stocks
     *
     * @param onlineShowStocks the value for baseinfo_company_store.Online_show_stocks
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setOnlineShowStocks(Integer onlineShowStocks) {
        this.onlineShowStocks = onlineShowStocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.Online_Reduce_after_payed
     *
     * @return the value of baseinfo_company_store.Online_Reduce_after_payed
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getOnlineReduceAfterPayed() {
        return onlineReduceAfterPayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.Online_Reduce_after_payed
     *
     * @param onlineReduceAfterPayed the value for baseinfo_company_store.Online_Reduce_after_payed
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setOnlineReduceAfterPayed(Integer onlineReduceAfterPayed) {
        this.onlineReduceAfterPayed = onlineReduceAfterPayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.created_at
     *
     * @return the value of baseinfo_company_store.created_at
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.created_at
     *
     * @param createdAt the value for baseinfo_company_store.created_at
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.updated_at
     *
     * @return the value of baseinfo_company_store.updated_at
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.updated_at
     *
     * @param updatedAt the value for baseinfo_company_store.updated_at
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getStoreTel() {
        return storeTel;
    }

    public void setStoreTel(String storeTel) {
        this.storeTel = storeTel;
    }

    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_store.is_deleted
     *
     * @return the value of baseinfo_company_store.is_deleted
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_store.is_deleted
     *
     * @param isDeleted the value for baseinfo_company_store.is_deleted
     * @mbg.generated Tue Apr 10 16:49:15 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getWeshopName() {
        return weshopName;
    }

    public void setWeshopName(String weshopName) {
        this.weshopName = weshopName;
    }

    public String getWeshopLogoImages() {
        return weshopLogoImages;
    }

    public void setWeshopLogoImages(String weshopLogoImages) {
        this.weshopLogoImages = weshopLogoImages;
    }

    public String getWeshopManagerName() {
        return weshopManagerName;
    }

    public void setWeshopManagerName(String weshopManagerName) {
        this.weshopManagerName = weshopManagerName;
    }

    public Long getWeshopManagerId() {
        return weshopManagerId;
    }

    public void setWeshopManagerId(Long weshopManagerId) {
        this.weshopManagerId = weshopManagerId;
    }

    public String getWeshopContactType() {
        return weshopContactType;
    }

    public void setWeshopContactType(String weshopContactType) {
        this.weshopContactType = weshopContactType;
    }

    public String getBusinessCategory() {
        return businessCategory;
    }

    public void setBusinessCategory(String businessCategory) {
        this.businessCategory = businessCategory;
    }

    public String getWeshopImages() {
        return weshopImages;
    }

    public void setWeshopImages(String weshopImages) {
        this.weshopImages = weshopImages;
    }

    public String getWeshopNotice() {
        return weshopNotice;
    }

    public void setWeshopNotice(String weshopNotice) {
        this.weshopNotice = weshopNotice;
    }

    public Integer getIsOpenWeshopNotice() {
        return isOpenWeshopNotice;
    }

    public void setIsOpenWeshopNotice(Integer isOpenWeshopNotice) {
        this.isOpenWeshopNotice = isOpenWeshopNotice;
    }

    public Integer getWeshopStatus() {
        return weshopStatus;
    }

    public void setWeshopStatus(Integer weshopStatus) {
        this.weshopStatus = weshopStatus;
    }

    public Integer getIsDeletedWeshop() {
        return isDeletedWeshop;
    }

    public void setIsDeletedWeshop(Integer isDeletedWeshop) {
        this.isDeletedWeshop = isDeletedWeshop;
    }

    public String getPrintIp() {
        return printIp;
    }

    public void setPrintIp(String printIp) {
        this.printIp = printIp;
    }

    public String getPrintPort() {
        return printPort;
    }

    public void setPrintPort(String printPort) {
        this.printPort = printPort;
    }

    public Integer getIsHasWeshop() {
        return isHasWeshop;
    }

    public void setIsHasWeshop(Integer isHasWeshop) {
        this.isHasWeshop = isHasWeshop;
    }

    public String getStoreNameSearch() {
        return storeNameSearch;
    }

    public void setStoreNameSearch(String storeNameSearch) {
        this.storeNameSearch = storeNameSearch;
    }

    public String getAlipayAccountQrcode() {
        return alipayAccountQrcode;
    }

    public void setAlipayAccountQrcode(String alipayAccountQrcode) {
        this.alipayAccountQrcode = alipayAccountQrcode;
    }

    public String getAlipayAccountQrcodeContent() {
        return alipayAccountQrcodeContent;
    }

    public void setAlipayAccountQrcodeContent(String alipayAccountQrcodeContent) {
        this.alipayAccountQrcodeContent = alipayAccountQrcodeContent;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Integer getExpireStatus() {
        return expireStatus;
    }

    public void setExpireStatus(Integer expireStatus) {
        this.expireStatus = expireStatus;
    }
}