package com.ihappy.partner.infrastructure.repo.mybatis.mapper;


import com.ihappy.partner.domain.dbdo.BaseinfoPartnerArrearsOrder;

public interface BaseinfoPartnerArrearsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_partner_arrears_order_0
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_partner_arrears_order_0
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    int insertSelective(BaseinfoPartnerArrearsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_partner_arrears_order_0
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    BaseinfoPartnerArrearsOrder selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_partner_arrears_order_0
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    int updateByPrimaryKeySelective(BaseinfoPartnerArrearsOrder record);

    /**
        * @Description: 根据支付流水查询
        * @Param:
        * @return:
        * @Author: zhangtengpo
        * @Date: 18-8-27 下午6:22
        */
    BaseinfoPartnerArrearsOrder selectByPayJournal(BaseinfoPartnerArrearsOrder record);
}