package com.ihappy.partner.infrastructure.repo.mybatis.mapper;


import com.ihappy.partner.domain.bo.level.CheckPartnerLevelBOByName;
import com.ihappy.partner.domain.dbdo.BaseinfoCompanyPartnerLevel;

import java.util.List;
import java.util.Map;

public interface BaseinfoCompanyPartnerLevelMapper {
    /**
     * 根据条件查询
     * @param record
     * @return
     */
    List<BaseinfoCompanyPartnerLevel> selectByCondition(BaseinfoCompanyPartnerLevel record);
    /**
     * 修改引用计数
     * @param paramMap
     * @return
     */
    Integer updateReferenceCount(Map<String, Object> paramMap);
    /**
     * 查询列表
     * @param record
     * @return
     */
    List<BaseinfoCompanyPartnerLevel> selectPartnerLevelList(BaseinfoCompanyPartnerLevel record);
    /**
     * 软删除
     * @param record
     * @return
     */
    Integer updateDelStatus(BaseinfoCompanyPartnerLevel record);

    /**
     * 查询单个详情
     * @param record
     * @return
     */
    BaseinfoCompanyPartnerLevel selectById(BaseinfoCompanyPartnerLevel record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_partner_level_0
     *
     * @mbg.generated Thu Apr 26 13:23:57 CST 2018
     */
    int deleteByPrimaryKey(Long partnerLevelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_partner_level_0
     *
     * @mbg.generated Thu Apr 26 13:23:57 CST 2018
     */
    int insert(BaseinfoCompanyPartnerLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_partner_level_0
     *
     * @mbg.generated Thu Apr 26 13:23:57 CST 2018
     */
    Integer insertSelective(BaseinfoCompanyPartnerLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_partner_level_0
     *
     * @mbg.generated Thu Apr 26 13:23:57 CST 2018
     */
    BaseinfoCompanyPartnerLevel selectByPrimaryKey(Long partnerLevelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_partner_level_0
     *
     * @mbg.generated Thu Apr 26 13:23:57 CST 2018
     */
    int updateByPrimaryKeySelective(BaseinfoCompanyPartnerLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_partner_level_0
     *
     * @mbg.generated Thu Apr 26 13:23:57 CST 2018
     */
    int updateByPrimaryKey(BaseinfoCompanyPartnerLevel record);

    /**
     * 判断名称是否重复
     * @param checkPartnerLevelBOByName
     * @return
     */
    List<BaseinfoCompanyPartnerLevel> checkPartnerLevelName(CheckPartnerLevelBOByName checkPartnerLevelBOByName);
}