package com.ihappy.partner.domain.dbdo;

public class BaseinfoPartnerArrearsOrder {
    /**
     * 真实订单编号
     */
    private String orderNo;
    /**
     * 订单类型
     */
    private String orderType;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_partner_arrears_order_0.order_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_partner_arrears_order_0.order_num
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_partner_arrears_order_0.partner_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    private Long partnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_partner_arrears_order_0.comp_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    private Integer compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_partner_arrears_order_0.money
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    private Long money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_partner_arrears_order_0.source_type
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    private Integer sourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_partner_arrears_order_0.income_type
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    private Integer incomeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_partner_arrears_order_0.created_at
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_partner_arrears_order_0.updated_at
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_partner_arrears_order_0.created_person_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_partner_arrears_order_0.updated_person_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_partner_arrears_order_0.is_deleted
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    private Boolean isDeleted;
    /**
     * 操作类型   0：保留值   null/1：欠款   2：预存款
     */
    private Integer type;

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getOrderType() {
        return orderType;
    }

    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_partner_arrears_order_0.order_id
     *
     * @return the value of baseinfo_partner_arrears_order_0.order_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_partner_arrears_order_0.order_id
     *
     * @param orderId the value for baseinfo_partner_arrears_order_0.order_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_partner_arrears_order_0.order_num
     *
     * @return the value of baseinfo_partner_arrears_order_0.order_num
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_partner_arrears_order_0.order_num
     *
     * @param orderNum the value for baseinfo_partner_arrears_order_0.order_num
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_partner_arrears_order_0.partner_id
     *
     * @return the value of baseinfo_partner_arrears_order_0.partner_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public Long getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_partner_arrears_order_0.partner_id
     *
     * @param partnerId the value for baseinfo_partner_arrears_order_0.partner_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public void setPartnerId(Long partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_partner_arrears_order_0.comp_id
     *
     * @return the value of baseinfo_partner_arrears_order_0.comp_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_partner_arrears_order_0.comp_id
     *
     * @param compId the value for baseinfo_partner_arrears_order_0.comp_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_partner_arrears_order_0.money
     *
     * @return the value of baseinfo_partner_arrears_order_0.money
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_partner_arrears_order_0.money
     *
     * @param money the value for baseinfo_partner_arrears_order_0.money
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_partner_arrears_order_0.source_type
     *
     * @return the value of baseinfo_partner_arrears_order_0.source_type
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_partner_arrears_order_0.source_type
     *
     * @param sourceType the value for baseinfo_partner_arrears_order_0.source_type
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_partner_arrears_order_0.income_type
     *
     * @return the value of baseinfo_partner_arrears_order_0.income_type
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public Integer getIncomeType() {
        return incomeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_partner_arrears_order_0.income_type
     *
     * @param incomeType the value for baseinfo_partner_arrears_order_0.income_type
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public void setIncomeType(Integer incomeType) {
        this.incomeType = incomeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_partner_arrears_order_0.created_at
     *
     * @return the value of baseinfo_partner_arrears_order_0.created_at
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_partner_arrears_order_0.created_at
     *
     * @param createdAt the value for baseinfo_partner_arrears_order_0.created_at
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_partner_arrears_order_0.updated_at
     *
     * @return the value of baseinfo_partner_arrears_order_0.updated_at
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_partner_arrears_order_0.updated_at
     *
     * @param updatedAt the value for baseinfo_partner_arrears_order_0.updated_at
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_partner_arrears_order_0.created_person_id
     *
     * @return the value of baseinfo_partner_arrears_order_0.created_person_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_partner_arrears_order_0.created_person_id
     *
     * @param createdPersonId the value for baseinfo_partner_arrears_order_0.created_person_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_partner_arrears_order_0.updated_person_id
     *
     * @return the value of baseinfo_partner_arrears_order_0.updated_person_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_partner_arrears_order_0.updated_person_id
     *
     * @param updatedPersonId the value for baseinfo_partner_arrears_order_0.updated_person_id
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_partner_arrears_order_0.is_deleted
     *
     * @return the value of baseinfo_partner_arrears_order_0.is_deleted
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_partner_arrears_order_0.is_deleted
     *
     * @param isDeleted the value for baseinfo_partner_arrears_order_0.is_deleted
     *
     * @mbg.generated Wed Apr 18 14:41:20 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}