package com.ihappy.partner.domain.dbdo;

import java.util.List;

public class BaseinfoCompanyPartner {
    /**
     * 微信号
     */
    private String wechatAccountName;

    private Integer limit;
    private Integer offset;
    /**
     * 交易总额  单位分
     */
    private Long dueAmount;
    /**
     * 待发货总数
     */
    private Long onthewayNumber;
    /**
     * 总交易件数
     */
    private Long totalNumber;
    /**
     * 交易单数
     */
    private Long orderCount;
    /**
     * 最长欠款时间
     */
    private Long debtDate;
    /**
     * 预存款
     */
    private Long prepaidDeposit;
    /**
     * 门店id
     */
    private List<Long> storeIds;
    /**
     * 性别 0 保密 1 男 2女
     */
    private Integer sex;
    /**
     * 生日
     */
    private String birthday;
    /**
     * 微信昵称
     */
    private String wechatNickname;
    /**
     * 禁用  0：未禁用  1：禁用
     */
    private Integer forbidden;
    /**
     * 会员编号
     */
    private String memberNo;
    /**
     * 开卡导购员id
     */
    private Long shoppingGuideId;
    /**
     * 门店id
     */
    private Long storeId;
    /**
     * 消费次数
     */
    private Integer consumptionTimes;
    /**
     * 查询字段
     */
    private String searchStr;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.partner_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Long partnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.partner_comp_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Integer partnerCompId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.partner_name
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String partnerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.is_favor
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Integer isFavor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.comp_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Integer compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.comp_name
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String compName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.partner_level_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Long partnerLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.partner_memo
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String partnerMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.partner_type
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Integer partnerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.sort
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.version
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.partner_arrears
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Long partnerArrears;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.partner_discount
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Integer partnerDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.mobile
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.created_at
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.updated_at
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.created_person_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.updated_person_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.is_deleted
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.partner_linkman
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String partnerLinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.province
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.city
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.zone
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String zone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.partner_address
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String partnerAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.bank_name
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.bank_account_name
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String bankAccountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.bank_account_number
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String bankAccountNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.mail
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_partner_0.fax
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    private String fax;

    private String headPortraitAddress;

    private String tel;

    private Long lastContactTime;

    private Integer isCanEdit;  // 是否可以编辑 0: 不可以 1: 可以

    private Integer isDefault;  // 是否是默认 0:不是默认 1: 是默认

    private Integer sellerRefundTimes;

    public Integer getSellerRefundTimes() {
        return sellerRefundTimes;
    }

    public void setSellerRefundTimes(Integer sellerRefundTimes) {
        this.sellerRefundTimes = sellerRefundTimes;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getOffset() {
        return offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Long getDueAmount() {
        return dueAmount;
    }

    public void setDueAmount(Long dueAmount) {
        this.dueAmount = dueAmount;
    }

    public Long getOnthewayNumber() {
        return onthewayNumber;
    }

    public void setOnthewayNumber(Long onthewayNumber) {
        this.onthewayNumber = onthewayNumber;
    }

    public Long getTotalNumber() {
        return totalNumber;
    }

    public void setTotalNumber(Long totalNumber) {
        this.totalNumber = totalNumber;
    }

    public Long getOrderCount() {
        return orderCount;
    }

    public void setOrderCount(Long orderCount) {
        this.orderCount = orderCount;
    }

    public Long getDebtDate() {
        return debtDate;
    }

    public void setDebtDate(Long debtDate) {
        this.debtDate = debtDate;
    }

    public Long getPrepaidDeposit() {
        return prepaidDeposit;
    }

    public void setPrepaidDeposit(Long prepaidDeposit) {
        this.prepaidDeposit = prepaidDeposit;
    }

    public List<Long> getStoreIds() {
        return storeIds;
    }

    public void setStoreIds(List<Long> storeIds) {
        this.storeIds = storeIds;
    }

    public Integer getIsDefault() {
        return isDefault;
    }

    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    public Integer getIsCanEdit() {
        return isCanEdit;
    }

    public void setIsCanEdit(Integer isCanEdit) {
        this.isCanEdit = isCanEdit;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getWechatNickname() {
        return wechatNickname;
    }

    public void setWechatNickname(String wechatNickname) {
        this.wechatNickname = wechatNickname;
    }

    public Integer getForbidden() {
        return forbidden;
    }

    public void setForbidden(Integer forbidden) {
        this.forbidden = forbidden;
    }

    public String getMemberNo() {
        return memberNo;
    }

    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo;
    }

    public Long getShoppingGuideId() {
        return shoppingGuideId;
    }

    public void setShoppingGuideId(Long shoppingGuideId) {
        this.shoppingGuideId = shoppingGuideId;
    }

    public Long getStoreId() {
        return storeId;
    }

    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    public Long getLastContactTime() {
        return lastContactTime;
    }

    public void setLastContactTime(Long lastContactTime) {
        this.lastContactTime = lastContactTime;
    }

    public String getSearchStr() {
        return searchStr;
    }

    public void setSearchStr(String searchStr) {
        this.searchStr = searchStr;
    }

    public Integer getConsumptionTimes() {
        return consumptionTimes;
    }

    public void setConsumptionTimes(Integer consumptionTimes) {
        this.consumptionTimes = consumptionTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.partner_id
     *
     * @return the value of baseinfo_company_partner_0.partner_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Long getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.partner_id
     *
     * @param partnerId the value for baseinfo_company_partner_0.partner_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setPartnerId(Long partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.partner_comp_id
     *
     * @return the value of baseinfo_company_partner_0.partner_comp_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Integer getPartnerCompId() {
        return partnerCompId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.partner_comp_id
     *
     * @param partnerCompId the value for baseinfo_company_partner_0.partner_comp_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setPartnerCompId(Integer partnerCompId) {
        this.partnerCompId = partnerCompId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.partner_name
     *
     * @return the value of baseinfo_company_partner_0.partner_name
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getPartnerName() {
        return partnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.partner_name
     *
     * @param partnerName the value for baseinfo_company_partner_0.partner_name
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setPartnerName(String partnerName) {
        this.partnerName = partnerName == null ? null : partnerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.is_favor
     *
     * @return the value of baseinfo_company_partner_0.is_favor
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Integer getIsFavor() {
        return isFavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.is_favor
     *
     * @param isFavor the value for baseinfo_company_partner_0.is_favor
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setIsFavor(Integer isFavor) {
        this.isFavor = isFavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.comp_id
     *
     * @return the value of baseinfo_company_partner_0.comp_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.comp_id
     *
     * @param compId the value for baseinfo_company_partner_0.comp_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.comp_name
     *
     * @return the value of baseinfo_company_partner_0.comp_name
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getCompName() {
        return compName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.comp_name
     *
     * @param compName the value for baseinfo_company_partner_0.comp_name
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setCompName(String compName) {
        this.compName = compName == null ? null : compName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.partner_level_id
     *
     * @return the value of baseinfo_company_partner_0.partner_level_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Long getPartnerLevelId() {
        return partnerLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.partner_level_id
     *
     * @param partnerLevelId the value for baseinfo_company_partner_0.partner_level_id
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setPartnerLevelId(Long partnerLevelId) {
        this.partnerLevelId = partnerLevelId == null ? null : partnerLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.partner_memo
     *
     * @return the value of baseinfo_company_partner_0.partner_memo
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getPartnerMemo() {
        return partnerMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.partner_memo
     *
     * @param partnerMemo the value for baseinfo_company_partner_0.partner_memo
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setPartnerMemo(String partnerMemo) {
        this.partnerMemo = partnerMemo == null ? null : partnerMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.partner_type
     *
     * @return the value of baseinfo_company_partner_0.partner_type
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Integer getPartnerType() {
        return partnerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.partner_type
     *
     * @param partnerType the value for baseinfo_company_partner_0.partner_type
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setPartnerType(Integer partnerType) {
        this.partnerType = partnerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.sort
     *
     * @return the value of baseinfo_company_partner_0.sort
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.sort
     *
     * @param sort the value for baseinfo_company_partner_0.sort
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.version
     *
     * @return the value of baseinfo_company_partner_0.version
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.version
     *
     * @param version the value for baseinfo_company_partner_0.version
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.partner_arrears
     *
     * @return the value of baseinfo_company_partner_0.partner_arrears
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Long getPartnerArrears() {
        return partnerArrears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.partner_arrears
     *
     * @param partnerArrears the value for baseinfo_company_partner_0.partner_arrears
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setPartnerArrears(Long partnerArrears) {
        this.partnerArrears = partnerArrears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.partner_discount
     *
     * @return the value of baseinfo_company_partner_0.partner_discount
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Integer getPartnerDiscount() {
        return partnerDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.partner_discount
     *
     * @param partnerDiscount the value for baseinfo_company_partner_0.partner_discount
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setPartnerDiscount(Integer partnerDiscount) {
        this.partnerDiscount = partnerDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.mobile
     *
     * @return the value of baseinfo_company_partner_0.mobile
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.mobile
     *
     * @param mobile the value for baseinfo_company_partner_0.mobile
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.created_at
     *
     * @return the value of baseinfo_company_partner_0.created_at
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.created_at
     *
     * @param createdAt the value for baseinfo_company_partner_0.created_at
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.updated_at
     *
     * @return the value of baseinfo_company_partner_0.updated_at
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.updated_at
     *
     * @param updatedAt the value for baseinfo_company_partner_0.updated_at
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }


    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.is_deleted
     *
     * @return the value of baseinfo_company_partner_0.is_deleted
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.is_deleted
     *
     * @param isDeleted the value for baseinfo_company_partner_0.is_deleted
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.partner_linkman
     *
     * @return the value of baseinfo_company_partner_0.partner_linkman
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getPartnerLinkman() {
        return partnerLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.partner_linkman
     *
     * @param partnerLinkman the value for baseinfo_company_partner_0.partner_linkman
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setPartnerLinkman(String partnerLinkman) {
        this.partnerLinkman = partnerLinkman == null ? null : partnerLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.province
     *
     * @return the value of baseinfo_company_partner_0.province
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.province
     *
     * @param province the value for baseinfo_company_partner_0.province
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.city
     *
     * @return the value of baseinfo_company_partner_0.city
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.city
     *
     * @param city the value for baseinfo_company_partner_0.city
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.zone
     *
     * @return the value of baseinfo_company_partner_0.zone
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.zone
     *
     * @param zone the value for baseinfo_company_partner_0.zone
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setZone(String zone) {
        this.zone = zone == null ? null : zone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.partner_address
     *
     * @return the value of baseinfo_company_partner_0.partner_address
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getPartnerAddress() {
        return partnerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.partner_address
     *
     * @param partnerAddress the value for baseinfo_company_partner_0.partner_address
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setPartnerAddress(String partnerAddress) {
        this.partnerAddress = partnerAddress == null ? null : partnerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.bank_name
     *
     * @return the value of baseinfo_company_partner_0.bank_name
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.bank_name
     *
     * @param bankName the value for baseinfo_company_partner_0.bank_name
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.bank_account_name
     *
     * @return the value of baseinfo_company_partner_0.bank_account_name
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getBankAccountName() {
        return bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.bank_account_name
     *
     * @param bankAccountName the value for baseinfo_company_partner_0.bank_account_name
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName == null ? null : bankAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.bank_account_number
     *
     * @return the value of baseinfo_company_partner_0.bank_account_number
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getBankAccountNumber() {
        return bankAccountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.bank_account_number
     *
     * @param bankAccountNumber the value for baseinfo_company_partner_0.bank_account_number
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setBankAccountNumber(String bankAccountNumber) {
        this.bankAccountNumber = bankAccountNumber == null ? null : bankAccountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.mail
     *
     * @return the value of baseinfo_company_partner_0.mail
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.mail
     *
     * @param mail the value for baseinfo_company_partner_0.mail
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_partner_0.fax
     *
     * @return the value of baseinfo_company_partner_0.fax
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_partner_0.fax
     *
     * @param fax the value for baseinfo_company_partner_0.fax
     *
     * @mbg.generated Sat Mar 31 13:47:34 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    public String getHeadPortraitAddress() {
        return headPortraitAddress;
    }

    public void setHeadPortraitAddress(String headPortraitAddress) {
        this.headPortraitAddress = headPortraitAddress;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getWechatAccountName() {
        return wechatAccountName;
    }

    public void setWechatAccountName(String wechatAccountName) {
        this.wechatAccountName = wechatAccountName;
    }
}