package com.ihappy.store.infrastructure.repo.mybatis.mapper.store;


import com.ihappy.store.domain.dbdo.store.BaseinfoCompanyStoreCt;

import java.util.List;
import java.util.Map;

public interface BaseinfoCompanyStoreCtMapper {

    List<BaseinfoCompanyStoreCt> selectListByCtIds(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_store_ct_0
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    int deleteByPrimaryKey(Long storeCtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_store_ct_0
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    int insert(BaseinfoCompanyStoreCt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_store_ct_0
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    int insertSelective(BaseinfoCompanyStoreCt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_store_ct_0
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    BaseinfoCompanyStoreCt selectByPrimaryKey(Long storeCtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_store_ct_0
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    int updateByPrimaryKeySelective(BaseinfoCompanyStoreCt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_company_store_ct_0
     *
     * @mbg.generated Fri Apr 27 14:19:11 CST 2018
     */
    int updateByPrimaryKey(BaseinfoCompanyStoreCt record);
}