package com.ihappy.store.domain.dbdo.weshop;

public class PersonWeshopCollectionPurchase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_weshop_collection_purchase_0.person_weshop_collection_purchase_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long personWeshopCollectionPurchaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_weshop_collection_purchase_0.person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_weshop_collection_purchase_0.weshop_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long weshopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_weshop_collection_purchase_0.is_collected
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Boolean isCollected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_weshop_collection_purchase_0.is_purchased
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Boolean isPurchased;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_weshop_collection_purchase_0.created_at
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_weshop_collection_purchase_0.updated_at
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_weshop_collection_purchase_0.created_person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_weshop_collection_purchase_0.updated_person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_weshop_collection_purchase_0.is_deleted
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_weshop_collection_purchase_0.person_weshop_collection_purchase_id
     *
     * @return the value of person_weshop_collection_purchase_0.person_weshop_collection_purchase_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getPersonWeshopCollectionPurchaseId() {
        return personWeshopCollectionPurchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_weshop_collection_purchase_0.person_weshop_collection_purchase_id
     *
     * @param personWeshopCollectionPurchaseId the value for person_weshop_collection_purchase_0.person_weshop_collection_purchase_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setPersonWeshopCollectionPurchaseId(Long personWeshopCollectionPurchaseId) {
        this.personWeshopCollectionPurchaseId = personWeshopCollectionPurchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_weshop_collection_purchase_0.person_id
     *
     * @return the value of person_weshop_collection_purchase_0.person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_weshop_collection_purchase_0.person_id
     *
     * @param personId the value for person_weshop_collection_purchase_0.person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_weshop_collection_purchase_0.weshop_id
     *
     * @return the value of person_weshop_collection_purchase_0.weshop_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getWeshopId() {
        return weshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_weshop_collection_purchase_0.weshop_id
     *
     * @param weshopId the value for person_weshop_collection_purchase_0.weshop_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setWeshopId(Long weshopId) {
        this.weshopId = weshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_weshop_collection_purchase_0.is_collected
     *
     * @return the value of person_weshop_collection_purchase_0.is_collected
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Boolean getIsCollected() {
        return isCollected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_weshop_collection_purchase_0.is_collected
     *
     * @param isCollected the value for person_weshop_collection_purchase_0.is_collected
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setIsCollected(Boolean isCollected) {
        this.isCollected = isCollected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_weshop_collection_purchase_0.is_purchased
     *
     * @return the value of person_weshop_collection_purchase_0.is_purchased
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Boolean getIsPurchased() {
        return isPurchased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_weshop_collection_purchase_0.is_purchased
     *
     * @param isPurchased the value for person_weshop_collection_purchase_0.is_purchased
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setIsPurchased(Boolean isPurchased) {
        this.isPurchased = isPurchased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_weshop_collection_purchase_0.created_at
     *
     * @return the value of person_weshop_collection_purchase_0.created_at
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_weshop_collection_purchase_0.created_at
     *
     * @param createdAt the value for person_weshop_collection_purchase_0.created_at
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_weshop_collection_purchase_0.updated_at
     *
     * @return the value of person_weshop_collection_purchase_0.updated_at
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_weshop_collection_purchase_0.updated_at
     *
     * @param updatedAt the value for person_weshop_collection_purchase_0.updated_at
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_weshop_collection_purchase_0.created_person_id
     *
     * @return the value of person_weshop_collection_purchase_0.created_person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_weshop_collection_purchase_0.created_person_id
     *
     * @param createdPersonId the value for person_weshop_collection_purchase_0.created_person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_weshop_collection_purchase_0.updated_person_id
     *
     * @return the value of person_weshop_collection_purchase_0.updated_person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_weshop_collection_purchase_0.updated_person_id
     *
     * @param updatedPersonId the value for person_weshop_collection_purchase_0.updated_person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_weshop_collection_purchase_0.is_deleted
     *
     * @return the value of person_weshop_collection_purchase_0.is_deleted
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_weshop_collection_purchase_0.is_deleted
     *
     * @param isDeleted the value for person_weshop_collection_purchase_0.is_deleted
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}