package com.ihappy.store.domain.dbdo.weshop;

public class WeshopVisit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_visit_0.weshop_visit_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long weshopVisitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_visit_0.weshop_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long weshopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_visit_0.visit_num
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Integer visitNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_visit_0.visit_person_num
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Integer visitPersonNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_visit_0.created_at
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_visit_0.updated_at
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_visit_0.created_person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_visit_0.updated_person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_visit_0.is_deleted
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_visit_0.comp_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    private Long compId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_visit_0.weshop_visit_id
     *
     * @return the value of weshop_visit_0.weshop_visit_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getWeshopVisitId() {
        return weshopVisitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_visit_0.weshop_visit_id
     *
     * @param weshopVisitId the value for weshop_visit_0.weshop_visit_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setWeshopVisitId(Long weshopVisitId) {
        this.weshopVisitId = weshopVisitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_visit_0.weshop_id
     *
     * @return the value of weshop_visit_0.weshop_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getWeshopId() {
        return weshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_visit_0.weshop_id
     *
     * @param weshopId the value for weshop_visit_0.weshop_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setWeshopId(Long weshopId) {
        this.weshopId = weshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_visit_0.visit_num
     *
     * @return the value of weshop_visit_0.visit_num
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Integer getVisitNum() {
        return visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_visit_0.visit_num
     *
     * @param visitNum the value for weshop_visit_0.visit_num
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setVisitNum(Integer visitNum) {
        this.visitNum = visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_visit_0.visit_person_num
     *
     * @return the value of weshop_visit_0.visit_person_num
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Integer getVisitPersonNum() {
        return visitPersonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_visit_0.visit_person_num
     *
     * @param visitPersonNum the value for weshop_visit_0.visit_person_num
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setVisitPersonNum(Integer visitPersonNum) {
        this.visitPersonNum = visitPersonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_visit_0.created_at
     *
     * @return the value of weshop_visit_0.created_at
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_visit_0.created_at
     *
     * @param createdAt the value for weshop_visit_0.created_at
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_visit_0.updated_at
     *
     * @return the value of weshop_visit_0.updated_at
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_visit_0.updated_at
     *
     * @param updatedAt the value for weshop_visit_0.updated_at
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_visit_0.created_person_id
     *
     * @return the value of weshop_visit_0.created_person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_visit_0.created_person_id
     *
     * @param createdPersonId the value for weshop_visit_0.created_person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_visit_0.updated_person_id
     *
     * @return the value of weshop_visit_0.updated_person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_visit_0.updated_person_id
     *
     * @param updatedPersonId the value for weshop_visit_0.updated_person_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_visit_0.is_deleted
     *
     * @return the value of weshop_visit_0.is_deleted
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_visit_0.is_deleted
     *
     * @param isDeleted the value for weshop_visit_0.is_deleted
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_visit_0.comp_id
     *
     * @return the value of weshop_visit_0.comp_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_visit_0.comp_id
     *
     * @param compId the value for weshop_visit_0.comp_id
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }
}