package com.ihappy.store.domain.dbdo.weshop;

public class WeshopCollectionJournal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_collection_journal_0.weshop_collection_journal_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    private Long weshopCollectionJournalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_collection_journal_0.visit_user_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    private Long visitUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_collection_journal_0.visit_token
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    private String visitToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_collection_journal_0.store_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    private Long storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_collection_journal_0.comp_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    private Long compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_collection_journal_0.collected_time
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    private Long collectedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_collection_journal_0.created_at
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_collection_journal_0.updated_at
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_collection_journal_0.created_person_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_collection_journal_0.updated_person_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    private Integer updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weshop_collection_journal_0.is_deleted
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_collection_journal_0.weshop_collection_journal_id
     *
     * @return the value of weshop_collection_journal_0.weshop_collection_journal_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public Long getWeshopCollectionJournalId() {
        return weshopCollectionJournalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_collection_journal_0.weshop_collection_journal_id
     *
     * @param weshopCollectionJournalId the value for weshop_collection_journal_0.weshop_collection_journal_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public void setWeshopCollectionJournalId(Long weshopCollectionJournalId) {
        this.weshopCollectionJournalId = weshopCollectionJournalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_collection_journal_0.visit_user_id
     *
     * @return the value of weshop_collection_journal_0.visit_user_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public Long getVisitUserId() {
        return visitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_collection_journal_0.visit_user_id
     *
     * @param visitUserId the value for weshop_collection_journal_0.visit_user_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public void setVisitUserId(Long visitUserId) {
        this.visitUserId = visitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_collection_journal_0.visit_token
     *
     * @return the value of weshop_collection_journal_0.visit_token
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public String getVisitToken() {
        return visitToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_collection_journal_0.visit_token
     *
     * @param visitToken the value for weshop_collection_journal_0.visit_token
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public void setVisitToken(String visitToken) {
        this.visitToken = visitToken == null ? null : visitToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_collection_journal_0.store_id
     *
     * @return the value of weshop_collection_journal_0.store_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_collection_journal_0.store_id
     *
     * @param storeId the value for weshop_collection_journal_0.store_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_collection_journal_0.comp_id
     *
     * @return the value of weshop_collection_journal_0.comp_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_collection_journal_0.comp_id
     *
     * @param compId the value for weshop_collection_journal_0.comp_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_collection_journal_0.collected_time
     *
     * @return the value of weshop_collection_journal_0.collected_time
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public Long getCollectedTime() {
        return collectedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_collection_journal_0.collected_time
     *
     * @param collectedTime the value for weshop_collection_journal_0.collected_time
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public void setCollectedTime(Long collectedTime) {
        this.collectedTime = collectedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_collection_journal_0.created_at
     *
     * @return the value of weshop_collection_journal_0.created_at
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_collection_journal_0.created_at
     *
     * @param createdAt the value for weshop_collection_journal_0.created_at
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_collection_journal_0.updated_at
     *
     * @return the value of weshop_collection_journal_0.updated_at
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_collection_journal_0.updated_at
     *
     * @param updatedAt the value for weshop_collection_journal_0.updated_at
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_collection_journal_0.created_person_id
     *
     * @return the value of weshop_collection_journal_0.created_person_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_collection_journal_0.created_person_id
     *
     * @param createdPersonId the value for weshop_collection_journal_0.created_person_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_collection_journal_0.updated_person_id
     *
     * @return the value of weshop_collection_journal_0.updated_person_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public Integer getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_collection_journal_0.updated_person_id
     *
     * @param updatedPersonId the value for weshop_collection_journal_0.updated_person_id
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public void setUpdatedPersonId(Integer updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weshop_collection_journal_0.is_deleted
     *
     * @return the value of weshop_collection_journal_0.is_deleted
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weshop_collection_journal_0.is_deleted
     *
     * @param isDeleted the value for weshop_collection_journal_0.is_deleted
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}