package com.ihappy.store.infrastructure.repo.mybatis.mapper.performance;


import com.ihappy.store.domain.bo.performance.SalePerformanceBO;
import com.ihappy.store.domain.dbdo.performance.SalePerformance;

import java.util.List;

public interface SalePerformanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_performance_1
     *
     * @mbg.generated Tue Aug 28 14:41:42 CST 2018
     */
    int deleteByPrimaryKey(Long salePerformanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_performance_1
     *
     * @mbg.generated Tue Aug 28 14:41:42 CST 2018
     */
    int insertSelective(SalePerformance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_performance_1
     *
     * @mbg.generated Tue Aug 28 14:41:42 CST 2018
     */
    SalePerformance selectByPrimaryKey(Long salePerformanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_performance_1
     *
     * @mbg.generated Tue Aug 28 14:41:42 CST 2018
     */
    int updateByPrimaryKeySelective(SalePerformance record);

    /**
     * 查询门店 当月绩效目标
     * @param bo
     * @return
     */
    List<SalePerformance> selectStorePerformance(SalePerformanceBO bo);

    /**
     * 查询员工业绩目标
     * @param bo compId,yearMonth,storeIds
     * @return
     */
    List<SalePerformance> selectSellerPerformance(SalePerformanceBO bo);

    /**
     * 插入更新
     * @param record
     * @return
     */
    int insertOrUpdateSelective(SalePerformanceBO record);

    /**
     * 分表计数
     * @param bo
     * @return
     */
    int selectShardingCount(SalePerformanceBO bo);
    /**
     * 分表查询
     * @param bo
     * @return
     */
    List<SalePerformance> selectSharding(SalePerformanceBO bo);

    /**
     * @Author sunjd
     * @Description 根据条件查询
     * @Date 14:55 2018/11/3
     * @Param [bo]
     * @return java.util.List<com.ihappy.store.domain.dbdo.performance.SalePerformance>
     **/
    List<SalePerformance> selectByCondition(SalePerformanceBO bo);
}