#初始化/修改 体验账号 公司/客户/供应商
#公司信息
INSERT INTO `comp_central`.`baseinfo_company` (`comp_id`, `comp_name`, `comp_short_name`, `comp_memo`, `region_id`, `region_name`, `area_id`, `province`, `province_id`, `ct_ids`, `ct_names`, `city_id`, `city`, `zone`, `legal_man`, `card_front_url`, `card_back_url`, `comp_address`, `comp_zip`, `license`, `license_picurl`, `comp_linkman`, `comp_linkman_tel`, `comp_sort`, `nature`, `is_platform`, `is_verified`, `verified_reason`, `verified_time`, `status`, `admin_person_id`, `admin_person_name`, `admin_person_mobile`, `tel`, `fax`, `mail`, `website`, `memo`, `comp_chit`, `comp_balance`, `business_category`, `created_at`, `updated_at`, `created_person_id`, `updated_person_id`, `is_deleted`, `bank_name`, `bank_account_name`, `bank_account_number`, `alipay_account_name`, `wechat_account_name`, `print_size`, `bill_name`, `wechat_account_qrcode`, `wechat_account_qrcode_content`, `wechat_receipt_qrcode`, `wechat_receipt_qrcode_content`, `alipay_account_qrcode`, `alipay_account_qrcode_content`, `alipay_receipt_qrcode`, `alipay_receipt_qrcode_content`, `print_bill`, `print_warn`, `allow_negative_on_hand_sell`) VALUES ('233', NULL, '一级批发商', '', '0', '', '0', '', '0', '1', '一级批发商', '0', '', '', '', '', '', '', '', '', '', '', '', '1', '1', '0', '0', '', '0', '1', '181', '王宝强', '77777777777', '', '', '', '', '', '0', '0', '1,2,3,4,5', '20180607112051', '20180607112051', '0', '0', '0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '提醒：钱款、件数请当面点清，离店概不负责，货物如有缺漏、损坏、到货请即通知，次品必需七天调换，不可退款，人为因素或逾期恕不退换，多谢合作！', '1');
INSERT INTO `comp_central`.`baseinfo_company` (`comp_id`, `comp_name`, `comp_short_name`, `comp_memo`, `region_id`, `region_name`, `area_id`, `province`, `province_id`, `ct_ids`, `ct_names`, `city_id`, `city`, `zone`, `legal_man`, `card_front_url`, `card_back_url`, `comp_address`, `comp_zip`, `license`, `license_picurl`, `comp_linkman`, `comp_linkman_tel`, `comp_sort`, `nature`, `is_platform`, `is_verified`, `verified_reason`, `verified_time`, `status`, `admin_person_id`, `admin_person_name`, `admin_person_mobile`, `tel`, `fax`, `mail`, `website`, `memo`, `comp_chit`, `comp_balance`, `business_category`, `created_at`, `updated_at`, `created_person_id`, `updated_person_id`, `is_deleted`, `bank_name`, `bank_account_name`, `bank_account_number`, `alipay_account_name`, `wechat_account_name`, `print_size`, `bill_name`, `wechat_account_qrcode`, `wechat_account_qrcode_content`, `wechat_receipt_qrcode`, `wechat_receipt_qrcode_content`, `alipay_account_qrcode`, `alipay_account_qrcode_content`, `alipay_receipt_qrcode`, `alipay_receipt_qrcode_content`, `print_bill`, `print_warn`, `allow_negative_on_hand_sell`) VALUES ('234', NULL, '二级批发商', '', '0', '', '0', '', '0', '2', '二级批发商', '0', '', '', '', '', '', '', '', '', '', '', '', '1', '1', '0', '0', '', '0', '1', '182', '吴彦祖', '77777777778', '', '', '', '', '', '0', '0', '5,4,3,2,1', '20180607112212', '20180607112212', '0', '0', '0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '提醒：钱款、件数请当面点清，离店概不负责，货物如有缺漏、损坏、到货请即通知，次品必需七天调换，不可退款，人为因素或逾期恕不退换，多谢合作！', '1');
INSERT INTO `comp_central`.`baseinfo_company` (`comp_id`, `comp_name`, `comp_short_name`, `comp_memo`, `region_id`, `region_name`, `area_id`, `province`, `province_id`, `ct_ids`, `ct_names`, `city_id`, `city`, `zone`, `legal_man`, `card_front_url`, `card_back_url`, `comp_address`, `comp_zip`, `license`, `license_picurl`, `comp_linkman`, `comp_linkman_tel`, `comp_sort`, `nature`, `is_platform`, `is_verified`, `verified_reason`, `verified_time`, `status`, `admin_person_id`, `admin_person_name`, `admin_person_mobile`, `tel`, `fax`, `mail`, `website`, `memo`, `comp_chit`, `comp_balance`, `business_category`, `created_at`, `updated_at`, `created_person_id`, `updated_person_id`, `is_deleted`, `bank_name`, `bank_account_name`, `bank_account_number`, `alipay_account_name`, `wechat_account_name`, `print_size`, `bill_name`, `wechat_account_qrcode`, `wechat_account_qrcode_content`, `wechat_receipt_qrcode`, `wechat_receipt_qrcode_content`, `alipay_account_qrcode`, `alipay_account_qrcode_content`, `alipay_receipt_qrcode`, `alipay_receipt_qrcode_content`, `print_bill`, `print_warn`, `allow_negative_on_hand_sell`) VALUES ('235', NULL, '零售商', '', '0', '', '0', '', '0', '3', '零售商', '0', '', '', '', '', '', '', '', '', '', '', '', '1', '1', '0', '0', '', '0', '1', '183', '沈婷婷', '77777777779', '', '', '', '', '', '0', '0', '5,4,3,2,1', '20180607112920', '20180607112920', '0', '0', '0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '提醒：钱款、件数请当面点清，离店概不负责，货物如有缺漏、损坏、到货请即通知，次品必需七天调换，不可退款，人为因素或逾期恕不退换，多谢合作！', '1');

#UPDATE `comp_central`.`baseinfo_company` SET `comp_id`='233', `comp_name`=NULL, `comp_short_name`='一级批发商', `comp_memo`='', `region_id`='0', `region_name`='', `area_id`='0', `province`='', `province_id`='0', `ct_ids`='1', `ct_names`='一级批发商', `city_id`='0', `city`='', `zone`='', `legal_man`='', `card_front_url`='', `card_back_url`='', `comp_address`='', `comp_zip`='', `license`='', `license_picurl`='', `comp_linkman`='', `comp_linkman_tel`='', `comp_sort`='1', `nature`='1', `is_platform`='0', `is_verified`='0', `verified_reason`='', `verified_time`='0', `status`='1', `admin_person_id`='181', `admin_person_name`='王宝强', `admin_person_mobile`='77777777777', `tel`='', `fax`='', `mail`='', `website`='', `memo`='', `comp_chit`='0', `comp_balance`='0', `business_category`='1,2,3,4,5', `created_at`='20180607112051', `updated_at`='20180607112051', `created_person_id`='0', `updated_person_id`='0', `is_deleted`='0', `bank_name`='', `bank_account_name`='', `bank_account_number`='', `alipay_account_name`='', `wechat_account_name`='', `print_size`='', `bill_name`='', `wechat_account_qrcode`='', `wechat_account_qrcode_content`='', `wechat_receipt_qrcode`='', `wechat_receipt_qrcode_content`='', `alipay_account_qrcode`='', `alipay_account_qrcode_content`='', `alipay_receipt_qrcode`='', `alipay_receipt_qrcode_content`='', `print_bill`='1', `print_warn`='提醒：钱款、件数请当面点清，离店概不负责，货物如有缺漏、损坏、到货请即通知，次品必需七天调换，不可退款，人为因素或逾期恕不退换，多谢合作！', `allow_negative_on_hand_sell`='1' WHERE (`comp_id`='233');
#UPDATE `comp_central`.`baseinfo_company` SET `comp_id`='234', `comp_name`=NULL, `comp_short_name`='二级批发商', `comp_memo`='', `region_id`='0', `region_name`='', `area_id`='0', `province`='', `province_id`='0', `ct_ids`='2', `ct_names`='二级批发商', `city_id`='0', `city`='', `zone`='', `legal_man`='', `card_front_url`='', `card_back_url`='', `comp_address`='', `comp_zip`='', `license`='', `license_picurl`='', `comp_linkman`='', `comp_linkman_tel`='', `comp_sort`='1', `nature`='1', `is_platform`='0', `is_verified`='0', `verified_reason`='', `verified_time`='0', `status`='1', `admin_person_id`='182', `admin_person_name`='吴彦祖', `admin_person_mobile`='77777777778', `tel`='', `fax`='', `mail`='', `website`='', `memo`='', `comp_chit`='0', `comp_balance`='0', `business_category`='5,4,3,2,1', `created_at`='20180607112212', `updated_at`='20180607112212', `created_person_id`='0', `updated_person_id`='0', `is_deleted`='0', `bank_name`='', `bank_account_name`='', `bank_account_number`='', `alipay_account_name`='', `wechat_account_name`='', `print_size`='', `bill_name`='', `wechat_account_qrcode`='', `wechat_account_qrcode_content`='', `wechat_receipt_qrcode`='', `wechat_receipt_qrcode_content`='', `alipay_account_qrcode`='', `alipay_account_qrcode_content`='', `alipay_receipt_qrcode`='', `alipay_receipt_qrcode_content`='', `print_bill`='1', `print_warn`='提醒：钱款、件数请当面点清，离店概不负责，货物如有缺漏、损坏、到货请即通知，次品必需七天调换，不可退款，人为因素或逾期恕不退换，多谢合作！', `allow_negative_on_hand_sell`='1' WHERE (`comp_id`='234');
#UPDATE `comp_central`.`baseinfo_company` SET `comp_id`='235', `comp_name`=NULL, `comp_short_name`='零售商', `comp_memo`='', `region_id`='0', `region_name`='', `area_id`='0', `province`='', `province_id`='0', `ct_ids`='3', `ct_names`='零售商', `city_id`='0', `city`='', `zone`='', `legal_man`='', `card_front_url`='', `card_back_url`='', `comp_address`='', `comp_zip`='', `license`='', `license_picurl`='', `comp_linkman`='', `comp_linkman_tel`='', `comp_sort`='1', `nature`='1', `is_platform`='0', `is_verified`='0', `verified_reason`='', `verified_time`='0', `status`='1', `admin_person_id`='183', `admin_person_name`='沈婷婷', `admin_person_mobile`='77777777779', `tel`='', `fax`='', `mail`='', `website`='', `memo`='', `comp_chit`='0', `comp_balance`='0', `business_category`='5,4,3,2,1', `created_at`='20180607112920', `updated_at`='20180607112920', `created_person_id`='0', `updated_person_id`='0', `is_deleted`='0', `bank_name`='', `bank_account_name`='', `bank_account_number`='', `alipay_account_name`='', `wechat_account_name`='', `print_size`='', `bill_name`='', `wechat_account_qrcode`='', `wechat_account_qrcode_content`='', `wechat_receipt_qrcode`='', `wechat_receipt_qrcode_content`='', `alipay_account_qrcode`='', `alipay_account_qrcode_content`='', `alipay_receipt_qrcode`='', `alipay_receipt_qrcode_content`='', `print_bill`='1', `print_warn`='提醒：钱款、件数请当面点清，离店概不负责，货物如有缺漏、损坏、到货请即通知，次品必需七天调换，不可退款，人为因素或逾期恕不退换，多谢合作！', `allow_negative_on_hand_sell`='1' WHERE (`comp_id`='235');

INSERT INTO `comp_central`.`baseinfo_company_partner_8` (`partner_id`, `partner_comp_id`, `partner_name`, `is_favor`, `comp_id`, `comp_name`, `partner_level_id`, `partner_memo`, `partner_type`, `sort`, `version`, `partner_arrears`, `partner_discount`, `mobile`, `created_at`, `updated_at`, `created_person_id`, `updated_person_id`, `is_deleted`, `partner_linkman`, `province`, `city`, `zone`, `partner_address`, `bank_name`, `bank_account_name`, `bank_account_number`, `mail`, `fax`, `head_portrait_address`, `tel`, `last_contact_time`, `consumption_times`, `wechat_nickname`, `forbidden`, `member_no`, `shopping_guide_id`, `store_id`, `sex`, `birthday`, `total_transaction_amount`, `is_can_edit`, `is_default`) VALUES ('4900233', '0', '我的工厂', '0', '233', '0', '0', '', '0', '1', '0', '9707100', '0', '', '20180607112051', '20180613153652', '0', '0', '0', '我的工厂', '', '', '', '', '', '', '', '', '', '', '', '20180613153652', '5', '', '0', '', '0', '0', '0', '', '0', '1', '1');
INSERT INTO `comp_central`.`baseinfo_company_partner_8` (`partner_id`, `partner_comp_id`, `partner_name`, `is_favor`, `comp_id`, `comp_name`, `partner_level_id`, `partner_memo`, `partner_type`, `sort`, `version`, `partner_arrears`, `partner_discount`, `mobile`, `created_at`, `updated_at`, `created_person_id`, `updated_person_id`, `is_deleted`, `partner_linkman`, `province`, `city`, `zone`, `partner_address`, `bank_name`, `bank_account_name`, `bank_account_number`, `mail`, `fax`, `head_portrait_address`, `tel`, `last_contact_time`, `consumption_times`, `wechat_nickname`, `forbidden`, `member_no`, `shopping_guide_id`, `store_id`, `sex`, `birthday`, `total_transaction_amount`, `is_can_edit`, `is_default`) VALUES ('10090233', '234', '吴彦祖', '0', '233', '0', '0', '', '1', '1', '0', '0', '0', '77777777778', '20180613134622', '20180613134622', '181', '0', '0', '吴彦祖', '', '', '', '', '', '', '', '', '', '/public/uploads/0/goods/20180613/201806131346203545290.jpeg', '', '0', '0', '', '0', '', '0', '0', '0', '', '0', '1', '0');

#UPDATE `comp_central`.`baseinfo_company_partner_8` SET `partner_id`='4900233', `partner_comp_id`='0', `partner_name`='我的工厂', `is_favor`='0', `comp_id`='233', `comp_name`='0', `partner_level_id`='0', `partner_memo`='', `partner_type`='0', `sort`='1', `version`='0', `partner_arrears`='9707100', `partner_discount`='0', `mobile`='', `created_at`='20180607112051', `updated_at`='20180613153652', `created_person_id`='0', `updated_person_id`='0', `is_deleted`='0', `partner_linkman`='我的工厂', `province`='', `city`='', `zone`='', `partner_address`='', `bank_name`='', `bank_account_name`='', `bank_account_number`='', `mail`='', `fax`='', `head_portrait_address`='', `tel`='', `last_contact_time`='20180613153652', `consumption_times`='5', `wechat_nickname`='', `forbidden`='0', `member_no`='', `shopping_guide_id`='0', `store_id`='0', `sex`='0', `birthday`='', `total_transaction_amount`='0', `is_can_edit`='1', `is_default`='1' WHERE (`partner_id`='4900233');
#UPDATE `comp_central`.`baseinfo_company_partner_8` SET `partner_id`='10090233', `partner_comp_id`='234', `partner_name`='吴彦祖', `is_favor`='0', `comp_id`='233', `comp_name`='0', `partner_level_id`='0', `partner_memo`='', `partner_type`='1', `sort`='1', `version`='0', `partner_arrears`='0', `partner_discount`='0', `mobile`='77777777778', `created_at`='20180613134622', `updated_at`='20180613134622', `created_person_id`='181', `updated_person_id`='0', `is_deleted`='0', `partner_linkman`='吴彦祖', `province`='', `city`='', `zone`='', `partner_address`='', `bank_name`='', `bank_account_name`='', `bank_account_number`='', `mail`='', `fax`='', `head_portrait_address`='/public/uploads/0/goods/20180613/201806131346203545290.jpeg', `tel`='', `last_contact_time`='0', `consumption_times`='0', `wechat_nickname`='', `forbidden`='0', `member_no`='', `shopping_guide_id`='0', `store_id`='0', `sex`='0', `birthday`='', `total_transaction_amount`='0', `is_can_edit`='1', `is_default`='0' WHERE (`partner_id`='10090233');

INSERT INTO `comp_central`.`baseinfo_company_partner_0` (`partner_id`, `partner_comp_id`, `partner_name`, `is_favor`, `comp_id`, `comp_name`, `partner_level_id`, `partner_memo`, `partner_type`, `sort`, `version`, `partner_arrears`, `partner_discount`, `mobile`, `created_at`, `updated_at`, `created_person_id`, `updated_person_id`, `is_deleted`, `partner_linkman`, `province`, `city`, `zone`, `partner_address`, `bank_name`, `bank_account_name`, `bank_account_number`, `mail`, `head_portrait_address`, `fax`, `tel`, `last_contact_time`, `consumption_times`, `wechat_nickname`, `forbidden`, `member_no`, `shopping_guide_id`, `store_id`, `sex`, `birthday`, `total_transaction_amount`, `is_can_edit`, `is_default`) VALUES ('10480234', '233', '王宝强', '0', '234', '0', '0', '', '0', '1', '0', '0', '0', '77777777777', '20180613153146', '20180613153146', '182', '0', '0', '王宝强', '', '', '', '', '', '', '', '', '', '', '', '0', '0', '', '0', '', '0', '0', '0', '', '0', '1', '0');
INSERT INTO `comp_central`.`baseinfo_company_partner_0` (`partner_id`, `partner_comp_id`, `partner_name`, `is_favor`, `comp_id`, `comp_name`, `partner_level_id`, `partner_memo`, `partner_type`, `sort`, `version`, `partner_arrears`, `partner_discount`, `mobile`, `created_at`, `updated_at`, `created_person_id`, `updated_person_id`, `is_deleted`, `partner_linkman`, `province`, `city`, `zone`, `partner_address`, `bank_name`, `bank_account_name`, `bank_account_number`, `mail`, `head_portrait_address`, `fax`, `tel`, `last_contact_time`, `consumption_times`, `wechat_nickname`, `forbidden`, `member_no`, `shopping_guide_id`, `store_id`, `sex`, `birthday`, `total_transaction_amount`, `is_can_edit`, `is_default`) VALUES ('10140234', '235', '沈婷婷', '0', '234', '0', '0', '', '1', '1', '0', '0', '0', '77777777779', '20180613135130', '20180613135130', '182', '0', '0', '沈婷婷', '', '', '', '', '', '', '', '', '/public/uploads/0/goods/20180613/201806131351002678722.jpeg', '', '', '0', '0', '', '0', '', '0', '0', '0', '', '0', '1', '0');

#UPDATE `comp_central`.`baseinfo_company_partner_0` SET `partner_id`='10480234', `partner_comp_id`='233', `partner_name`='王宝强', `is_favor`='0', `comp_id`='234', `comp_name`='0', `partner_level_id`='0', `partner_memo`='', `partner_type`='0', `sort`='1', `version`='0', `partner_arrears`='0', `partner_discount`='0', `mobile`='77777777777', `created_at`='20180613153146', `updated_at`='20180613153146', `created_person_id`='182', `updated_person_id`='0', `is_deleted`='0', `partner_linkman`='王宝强', `province`='', `city`='', `zone`='', `partner_address`='', `bank_name`='', `bank_account_name`='', `bank_account_number`='', `mail`='', `head_portrait_address`='', `fax`='', `tel`='', `last_contact_time`='0', `consumption_times`='0', `wechat_nickname`='', `forbidden`='0', `member_no`='', `shopping_guide_id`='0', `store_id`='0', `sex`='0', `birthday`='', `total_transaction_amount`='0', `is_can_edit`='1', `is_default`='0' WHERE (`partner_id`='10480234');
#UPDATE `comp_central`.`baseinfo_company_partner_0` SET `partner_id`='10140234', `partner_comp_id`='235', `partner_name`='沈婷婷', `is_favor`='0', `comp_id`='234', `comp_name`='0', `partner_level_id`='0', `partner_memo`='', `partner_type`='1', `sort`='1', `version`='0', `partner_arrears`='0', `partner_discount`='0', `mobile`='77777777779', `created_at`='20180613135130', `updated_at`='20180613135130', `created_person_id`='182', `updated_person_id`='0', `is_deleted`='0', `partner_linkman`='沈婷婷', `province`='', `city`='', `zone`='', `partner_address`='', `bank_name`='', `bank_account_name`='', `bank_account_number`='', `mail`='', `head_portrait_address`='/public/uploads/0/goods/20180613/201806131351002678722.jpeg', `fax`='', `tel`='', `last_contact_time`='0', `consumption_times`='0', `wechat_nickname`='', `forbidden`='0', `member_no`='', `shopping_guide_id`='0', `store_id`='0', `sex`='0', `birthday`='', `total_transaction_amount`='0', `is_can_edit`='1', `is_default`='0' WHERE (`partner_id`='10140234');

INSERT INTO `comp_central`.`baseinfo_company_partner_1` (`partner_id`, `partner_comp_id`, `partner_name`, `is_favor`, `comp_id`, `comp_name`, `partner_level_id`, `partner_memo`, `partner_type`, `sort`, `version`, `partner_arrears`, `partner_discount`, `mobile`, `created_at`, `updated_at`, `created_person_id`, `updated_person_id`, `is_deleted`, `partner_linkman`, `province`, `city`, `zone`, `partner_address`, `bank_name`, `bank_account_name`, `bank_account_number`, `mail`, `fax`, `head_portrait_address`, `tel`, `last_contact_time`, `consumption_times`, `wechat_nickname`, `forbidden`, `member_no`, `shopping_guide_id`, `store_id`, `sex`, `birthday`, `total_transaction_amount`, `is_can_edit`, `is_default`) VALUES ('10490235', '234', '吴彦祖', '0', '235', '0', '0', '', '0', '1', '0', '0', '0', '77777777777', '20180613153237', '20180613153237', '183', '0', '0', '沈婷婷', '', '', '', '', '', '', '', '', '', '', '', '0', '0', '', '0', '', '0', '0', '0', '', '0', '1', '0');
INSERT INTO `comp_central`.`baseinfo_company_partner_1` (`partner_id`, `partner_comp_id`, `partner_name`, `is_favor`, `comp_id`, `comp_name`, `partner_level_id`, `partner_memo`, `partner_type`, `sort`, `version`, `partner_arrears`, `partner_discount`, `mobile`, `created_at`, `updated_at`, `created_person_id`, `updated_person_id`, `is_deleted`, `partner_linkman`, `province`, `city`, `zone`, `partner_address`, `bank_name`, `bank_account_name`, `bank_account_number`, `mail`, `fax`, `head_portrait_address`, `tel`, `last_contact_time`, `consumption_times`, `wechat_nickname`, `forbidden`, `member_no`, `shopping_guide_id`, `store_id`, `sex`, `birthday`, `total_transaction_amount`, `is_can_edit`, `is_default`) VALUES ('10000235', '0', '刘亦菲', '0', '235', '0', '1280235', '天仙', '2', '1', '0', '0', '0', '77777777710', '20180613133154', '20180613133154', '183', '183', '0', '', '', '', '', '', '', '', '', '', '', '', '', '0', '0', '', '0', '10000235', '183', '2050235', '2', '2018-06-13', '0', '1', '0');

#UPDATE `comp_central`.`baseinfo_company_partner_1` SET `partner_id`='10490235', `partner_comp_id`='234', `partner_name`='吴彦祖', `is_favor`='0', `comp_id`='235', `comp_name`='0', `partner_level_id`='0', `partner_memo`='', `partner_type`='0', `sort`='1', `version`='0', `partner_arrears`='0', `partner_discount`='0', `mobile`='77777777777', `created_at`='20180613153237', `updated_at`='20180613153237', `created_person_id`='183', `updated_person_id`='0', `is_deleted`='0', `partner_linkman`='沈婷婷', `province`='', `city`='', `zone`='', `partner_address`='', `bank_name`='', `bank_account_name`='', `bank_account_number`='', `mail`='', `fax`='', `head_portrait_address`='', `tel`='', `last_contact_time`='0', `consumption_times`='0', `wechat_nickname`='', `forbidden`='0', `member_no`='', `shopping_guide_id`='0', `store_id`='0', `sex`='0', `birthday`='', `total_transaction_amount`='0', `is_can_edit`='1', `is_default`='0' WHERE (`partner_id`='10490235');
#UPDATE `comp_central`.`baseinfo_company_partner_1` SET `partner_id`='10000235', `partner_comp_id`='0', `partner_name`='刘亦菲', `is_favor`='0', `comp_id`='235', `comp_name`='0', `partner_level_id`='1280235', `partner_memo`='天仙', `partner_type`='2', `sort`='1', `version`='0', `partner_arrears`='0', `partner_discount`='0', `mobile`='77777777710', `created_at`='20180613133154', `updated_at`='20180613133154', `created_person_id`='183', `updated_person_id`='183', `is_deleted`='0', `partner_linkman`='', `province`='', `city`='', `zone`='', `partner_address`='', `bank_name`='', `bank_account_name`='', `bank_account_number`='', `mail`='', `fax`='', `head_portrait_address`='', `tel`='', `last_contact_time`='0', `consumption_times`='0', `wechat_nickname`='', `forbidden`='0', `member_no`='10000235', `shopping_guide_id`='183', `store_id`='2050235', `sex`='2', `birthday`='2018-06-13', `total_transaction_amount`='0', `is_can_edit`='1', `is_default`='0' WHERE (`partner_id`='10000235');


# 修正 org 表org_ no 包含空格  2018-6-18 孙缙东  范围:baseinfo_company_org_0-8
ALTER TABLE `baseinfo_company_org_0`
CHANGE COLUMN `org_ no` `org_no`  varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '组织架构编号' AFTER `org_path`;

# 修改角色文案 2018-6-22 孙缙东  范围:baseinfo_company_role_0-8
update baseinfo_company_role_0 set role_name = '合伙人',role_memo='合伙人' where role_name='老板/合伙人';
update baseinfo_company_role_1 set role_name = '合伙人',role_memo='合伙人' where role_name='老板/合伙人';
update baseinfo_company_role_2 set role_name = '合伙人',role_memo='合伙人' where role_name='老板/合伙人';
update baseinfo_company_role_3 set role_name = '合伙人',role_memo='合伙人' where role_name='老板/合伙人';
update baseinfo_company_role_4 set role_name = '合伙人',role_memo='合伙人' where role_name='老板/合伙人';
update baseinfo_company_role_5 set role_name = '合伙人',role_memo='合伙人' where role_name='老板/合伙人';

#刷新角色 role_no
update baseinfo_company_role_0 set role_no = '1' where role_name = '合伙人' and is_default = 1;
update baseinfo_company_role_1 set role_no = '1' where role_name = '合伙人' and is_default = 1;
update baseinfo_company_role_2 set role_no = '1' where role_name = '合伙人' and is_default = 1;
update baseinfo_company_role_3 set role_no = '1' where role_name = '合伙人' and is_default = 1;
update baseinfo_company_role_4 set role_no = '1' where role_name = '合伙人' and is_default = 1;
update baseinfo_company_role_5 set role_no = '1' where role_name = '合伙人' and is_default = 1;

update baseinfo_company_role_0 set role_no = '2' where role_name = '店长' and is_default = 1;
update baseinfo_company_role_1 set role_no = '2' where role_name = '店长' and is_default = 1;
update baseinfo_company_role_2 set role_no = '2' where role_name = '店长' and is_default = 1;
update baseinfo_company_role_3 set role_no = '2' where role_name = '店长' and is_default = 1;
update baseinfo_company_role_4 set role_no = '2' where role_name = '店长' and is_default = 1;
update baseinfo_company_role_5 set role_no = '2' where role_name = '店长' and is_default = 1;

update baseinfo_company_role_0 set role_no = '3' where role_name = '店员' and is_default = 1;
update baseinfo_company_role_1 set role_no = '3' where role_name = '店员' and is_default = 1;
update baseinfo_company_role_2 set role_no = '3' where role_name = '店员' and is_default = 1;
update baseinfo_company_role_3 set role_no = '3' where role_name = '店员' and is_default = 1;
update baseinfo_company_role_4 set role_no = '3' where role_name = '店员' and is_default = 1;
update baseinfo_company_role_5 set role_no = '3' where role_name = '店员' and is_default = 1;

update baseinfo_company_role_0 set role_no = '4' where role_name = '工厂管理员' and is_default = 1;
update baseinfo_company_role_1 set role_no = '4' where role_name = '工厂管理员' and is_default = 1;
update baseinfo_company_role_2 set role_no = '4' where role_name = '工厂管理员' and is_default = 1;
update baseinfo_company_role_3 set role_no = '4' where role_name = '工厂管理员' and is_default = 1;
update baseinfo_company_role_4 set role_no = '4' where role_name = '工厂管理员' and is_default = 1;
update baseinfo_company_role_5 set role_no = '4' where role_name = '工厂管理员' and is_default = 1;

update baseinfo_company_role_0 set role_no = '5' where role_name = '商品管理员' and is_default = 1;
update baseinfo_company_role_1 set role_no = '5' where role_name = '商品管理员' and is_default = 1;
update baseinfo_company_role_2 set role_no = '5' where role_name = '商品管理员' and is_default = 1;
update baseinfo_company_role_3 set role_no = '5' where role_name = '商品管理员' and is_default = 1;
update baseinfo_company_role_4 set role_no = '5' where role_name = '商品管理员' and is_default = 1;
update baseinfo_company_role_5 set role_no = '5' where role_name = '商品管理员' and is_default = 1;

update baseinfo_company_role_0 set role_no = '13' where role_name = '面辅料管理员' and is_default = 1;
update baseinfo_company_role_1 set role_no = '13' where role_name = '面辅料管理员' and is_default = 1;
update baseinfo_company_role_2 set role_no = '13' where role_name = '面辅料管理员' and is_default = 1;
update baseinfo_company_role_3 set role_no = '13' where role_name = '面辅料管理员' and is_default = 1;
update baseinfo_company_role_4 set role_no = '13' where role_name = '面辅料管理员' and is_default = 1;
update baseinfo_company_role_5 set role_no = '13' where role_name = '面辅料管理员' and is_default = 1;