package com.ihappy.company.infrastructure.repo.mybatis.mapper.sys;

import com.ihappy.company.domain.bo.SysCompanyTypeBO;
import com.ihappy.company.domain.dbdo.SysCompanyType;

import java.util.List;
import java.util.Map;

public interface SysCompanyTypeMapper {
    /**
     * @param map
     * @return
     */
    List<SysCompanyType> selectList(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_type
     *
     * @mbg.generated Wed May 16 11:31:29 CST 2018
     */
    int deleteByPrimaryKey(Integer ctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_type
     *
     * @mbg.generated Wed May 16 11:31:29 CST 2018
     */
    int insert(SysCompanyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_type
     *
     * @mbg.generated Wed May 16 11:31:29 CST 2018
     */
    int insertSelective(SysCompanyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_type
     *
     * @mbg.generated Wed May 16 11:31:29 CST 2018
     */
    SysCompanyType selectByPrimaryKey(Integer ctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_type
     *
     * @mbg.generated Wed May 16 11:31:29 CST 2018
     */
    int updateByPrimaryKeySelective(SysCompanyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_type
     *
     * @mbg.generated Wed May 16 11:31:29 CST 2018
     */
    int updateByPrimaryKey(SysCompanyType record);


    /**
     *
     * @return
     */
    List<SysCompanyType> selectByCompanyTypeList();

    /**
     * 根据ctid查询系统公司类型信息列表
     * @param sysCompanyTypeBO
     * @return
     */
    List<SysCompanyType> selectSysCompanyTypeList(SysCompanyTypeBO sysCompanyTypeBO);

    /**
     * 根据ctid查询系统公司类型信息
     * @param sysCompanyTypeBO
     * @return
     */
    SysCompanyType selectOneSysCompanyTypeByCtId(SysCompanyTypeBO sysCompanyTypeBO);
}