package com.ihappy.company.infrastructure.repo.mybatis.mapper.sys;

import com.ihappy.company.domain.dbdo.SysCompanyTypePrintBill;

import java.util.List;

public interface SysCompanyTypePrintBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_type_print_bill
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    int deleteByPrimaryKey(Long pbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_type_print_bill
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    int insert(SysCompanyTypePrintBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_type_print_bill
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    int insertSelective(SysCompanyTypePrintBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_type_print_bill
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    SysCompanyTypePrintBill selectByPrimaryKey(Long pbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_type_print_bill
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    int updateByPrimaryKeySelective(SysCompanyTypePrintBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company_type_print_bill
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    int updateByPrimaryKey(SysCompanyTypePrintBill record);

     /**
       * @Description: 根据业务类型id查询对应的打印单据类型
       * @Param:
       * @return:
       * @Author: zhangtengpo 
       * @Date: 2018/6/4
       */
    List<SysCompanyTypePrintBill> selectByCtId(int ctId);
}