package com.ihappy.company.infrastructure.repo.mybatis.mapper.sys;

import com.ihappy.company.domain.dbdo.SysGoodsCategory;

import java.util.List;
import java.util.Map;

public interface SysGoodsCategoryMapper {
    /**
     * 根据map条件查询列表
     * @param map
     * @return
     */
    List<SysGoodsCategory> selectList(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_goods_category
     *
     * @mbg.generated Wed May 16 11:27:02 CST 2018
     */
    int deleteByPrimaryKey(Long gcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_goods_category
     *
     * @mbg.generated Wed May 16 11:27:02 CST 2018
     */
    int insert(SysGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_goods_category
     *
     * @mbg.generated Wed May 16 11:27:02 CST 2018
     */
    int insertSelective(SysGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_goods_category
     *
     * @mbg.generated Wed May 16 11:27:02 CST 2018
     */
    SysGoodsCategory selectByPrimaryKey(Long gcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_goods_category
     *
     * @mbg.generated Wed May 16 11:27:02 CST 2018
     */
    int updateByPrimaryKeySelective(SysGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_goods_category
     *
     * @mbg.generated Wed May 16 11:27:02 CST 2018
     */
    int updateByPrimaryKey(SysGoodsCategory record);
}