package com.ihappy.company.domain.dbdo;

public class BaseinfoCompanyBrand {
    private Integer limit;
    private Integer offset;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.brand_id
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.brand_name
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.brand _picurl
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private String brandPicurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.brand_ license
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private String brandLicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.brand_license_picurl
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private String brandLicensePicurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.brand_sort
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private Integer brandSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.comp_id
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private Integer compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.created_at
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.updated_at
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.created_person_id
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.updated_person_id
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.is_deleted
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_brand.brand _memo
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    private String brandMemo;

    public Integer getLimit() {
        return limit;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getOffset() {
        return offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_brand.brand_id
     *
     * @return the value of baseinfo_company_brand.brand_id
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_brand.brand_id
     *
     * @param brandId the value for baseinfo_company_brand.brand_id
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_brand.brand_name
     *
     * @return the value of baseinfo_company_brand.brand_name
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_brand.brand_name
     *
     * @param brandName the value for baseinfo_company_brand.brand_name
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_brand.brand _picurl
     *
     * @return the value of baseinfo_company_brand.brand _picurl
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public String getBrandPicurl() {
        return brandPicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_brand.brand _picurl
     *
     * @param brandPicurl the value for baseinfo_company_brand.brand _picurl
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public void setBrandPicurl(String brandPicurl) {
        this.brandPicurl = brandPicurl == null ? null : brandPicurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_brand.brand_ license
     *
     * @return the value of baseinfo_company_brand.brand_ license
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public String getBrandLicense() {
        return brandLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_brand.brand_ license
     *
     * @param brandLicense the value for baseinfo_company_brand.brand_ license
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public void setBrandLicense(String brandLicense) {
        this.brandLicense = brandLicense == null ? null : brandLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_brand.brand_license_picurl
     *
     * @return the value of baseinfo_company_brand.brand_license_picurl
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public String getBrandLicensePicurl() {
        return brandLicensePicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_brand.brand_license_picurl
     *
     * @param brandLicensePicurl the value for baseinfo_company_brand.brand_license_picurl
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public void setBrandLicensePicurl(String brandLicensePicurl) {
        this.brandLicensePicurl = brandLicensePicurl == null ? null : brandLicensePicurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_brand.brand_sort
     *
     * @return the value of baseinfo_company_brand.brand_sort
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public Integer getBrandSort() {
        return brandSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_brand.brand_sort
     *
     * @param brandSort the value for baseinfo_company_brand.brand_sort
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public void setBrandSort(Integer brandSort) {
        this.brandSort = brandSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_brand.comp_id
     *
     * @return the value of baseinfo_company_brand.comp_id
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_brand.comp_id
     *
     * @param compId the value for baseinfo_company_brand.comp_id
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public Long getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    public Boolean getDeleted() {
        return isDeleted;
    }

    public void setDeleted(Boolean deleted) {
        isDeleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_brand.is_deleted
     *
     * @return the value of baseinfo_company_brand.is_deleted
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_brand.is_deleted
     *
     * @param isDeleted the value for baseinfo_company_brand.is_deleted
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_brand.brand _memo
     *
     * @return the value of baseinfo_company_brand.brand _memo
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public String getBrandMemo() {
        return brandMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_brand.brand _memo
     *
     * @param brandMemo the value for baseinfo_company_brand.brand _memo
     *
     * @mbg.generated Tue Apr 03 13:18:15 CST 2018
     */
    public void setBrandMemo(String brandMemo) {
        this.brandMemo = brandMemo == null ? null : brandMemo.trim();
    }
}