package com.ihappy.company.domain.dbdo;

import com.ihappy.item.common.util.AttributeUtil;

import java.util.HashMap;
import java.util.Map;

public class BaseinfoCompany {

    /**
     * 打印模式1-蓝牙 2-服务
     */
    private Integer printMode;
    private String compLinkTel;
    /**
     * 公司头像
     */
    private String companyHead;
    private Integer limit;
    private Integer offset;
    /**
     * 版本号
     */
    private Integer version;
    /**
     * 付款备注
     */
    private String payRemark;
    /**
     * 付款备注者 姓名
     */
    private String payRemarkUserName;
    /**
     * 付款备注者 id
     */
    private Long payRemarkUserId;
    /**
     * 付款备注时间
     */
    private Long payRemarkTime;
    /**
     * 城市id
     */
    private Integer cityId;
    /**
     * 省份id
     */
    private Integer provinceId;
    /**
     * 企业法人
     */
    private String legalMan;
    /**
     * 允许负库存销售标志  0：不允许  1：允许   默认：允许
     */
    private Integer allowNegativeOnHandSell;
    /**
     * 打印提醒
     * 提醒：钱款、件数请当面点清，离店概不负责，货物如有缺漏、损坏、到货请即通知，次品必需七天调换，不可退款，人为因素或逾期恕不退换，多谢合作！
     */
    private String printWarn;
    /**
     * 是否打印账单 0：否  1：是（数据库默认1）
     */
    private Integer printBill;
    /**
     * 微信账号二维码
     */
    private String wechatAccountQrcode;
    /**
     * 微信账号二维码内容
     */
    private String wechatAccountQrcodeContent;
    /**
     * 微信收款码
     */
    private String wechatReceiptQrcode;
    /**
     * 微信收款码内容
     */
    private String wechatReceiptQrcodeContent;
    /**
     * 支付宝账号二维码
     */
    private String alipayAccountQrcode;
    /**
     * 支付宝账号二维码内容
     */
    private String alipayAccountQrcodeContent;
    /**
     * 支付宝收款码
     */
    private String alipayReceiptQrcode;
    /**
     * 支付宝收款码内容
     */
    private String alipayReceiptQrcodeContent;

    /**
     * 开户银行
     */
    private String bankName;
    /**
     * 账户名称
     */
    private String bankAccountName;
    /**
     * 银行账号
     */
    private String bankAccountNumber;
    /**
     * 支付宝账号
     */
    private String alipayAccountName;
    /**
     * 微信账号
     */
    private String wechatAccountName;
    /**
     * 打印尺寸
     */
    private String printSize;
    /**
     * 单据名称
     */
    private String billName;

    /**
     * 公司业务分类名  多个以逗号隔开
     */
    private String ctNames;
    /**
     * 公司业务分类id  多个以逗号隔开
     */
    private String ctIds;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.comp_id
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */

    private Integer compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.comp_name
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String compName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.comp_short_name
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String compShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.region_id
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.region_name
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.area_id
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.province
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.city
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.zone
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String zone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.comp_address
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String compAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.comp_zip
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String compZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.license
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String license;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.license_picurl
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String licensePicurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.comp_linkman
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String compLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.comp_linkman_tel
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String compLinkmanTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.comp_sort
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Integer compSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.nature
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Integer nature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.is_platform
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Integer isPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.is_verified
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Integer isVerified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.verified_reason
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String verifiedReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.verified_time
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Integer verifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.status
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.admin_person_id
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Long adminPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.admin_person_name
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String adminPersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.admin_person_mobile
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String adminPersonMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.tel
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.fax
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.mail
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.website
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.memo
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.comp_chit
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Integer compChit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.comp_balance
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Integer compBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.business_category
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String businessCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.created_at
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Long createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.updated_at
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Long updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.created_person_id
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Long createdPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.updated_person_id
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Long updatedPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.is_deleted
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company.comp_memo
     *
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    private String compMemo;
    /**
     * 身份证正面url
     */
    private String cardFrontUrl;
    /**
     * 身份证反面url
     */
    private String cardBackUrl;

    /**
     * 过期时间
     */
    private Long expireDate;

    /**
     * 0:付费;1:永久
     */
    private Integer expireStatus;

    /**
     * 0：测试用户 1：线上用户
     */
    private Integer onlineOrTest;
    /**
     * 销售单是否通知供应商
     */
    private Integer orderSellerNotify;
    /**
     * 采购单是否通知供应商
     */
    private Integer orderBuyerNotify;
    /*
     *
     *
     */
    private Map<String, String> attributes = new HashMap<>();

    public Integer getOrderSellerNotify() {
        return orderSellerNotify;
    }

    public void setOrderSellerNotify(Integer orderSellerNotify) {
        this.orderSellerNotify = orderSellerNotify;
    }

    public Integer getOrderBuyerNotify() {
        return orderBuyerNotify;
    }

    public void setOrderBuyerNotify(Integer orderBuyerNotify) {
        this.orderBuyerNotify = orderBuyerNotify;
    }

    public Integer getPrintMode() {
        return printMode;
    }

    public void setPrintMode(Integer printMode) {
        this.printMode = printMode;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getOffset() {
        return offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getPayRemark() {
        return payRemark;
    }

    public void setPayRemark(String payRemark) {
        this.payRemark = payRemark;
    }

    public String getPayRemarkUserName() {
        return payRemarkUserName;
    }

    public void setPayRemarkUserName(String payRemarkUserName) {
        this.payRemarkUserName = payRemarkUserName;
    }

    public Long getPayRemarkUserId() {
        return payRemarkUserId;
    }

    public void setPayRemarkUserId(Long payRemarkUserId) {
        this.payRemarkUserId = payRemarkUserId;
    }

    public Long getPayRemarkTime() {
        return payRemarkTime;
    }

    public void setPayRemarkTime(Long payRemarkTime) {
        this.payRemarkTime = payRemarkTime;
    }

    public Long getExpireDate() {
        return expireDate;
    }

    public void setExpireDate(Long expireDate) {
        this.expireDate = expireDate;
    }

    public String getCardFrontUrl() {
        return cardFrontUrl;
    }

    public void setCardFrontUrl(String cardFrontUrl) {
        this.cardFrontUrl = cardFrontUrl;
    }

    public String getCardBackUrl() {
        return cardBackUrl;
    }

    public void setCardBackUrl(String cardBackUrl) {
        this.cardBackUrl = cardBackUrl;
    }

    public String getLegalMan() {
        return legalMan;
    }

    public void setLegalMan(String legalMan) {
        this.legalMan = legalMan;
    }

    public Integer getAllowNegativeOnHandSell() {
        return allowNegativeOnHandSell;
    }

    public void setAllowNegativeOnHandSell(Integer allowNegativeOnHandSell) {
        this.allowNegativeOnHandSell = allowNegativeOnHandSell;
    }

    public String getPrintWarn() {
        return printWarn;
    }

    public void setPrintWarn(String printWarn) {
        this.printWarn = printWarn;
    }

    public Integer getPrintBill() {
        return printBill;
    }

    public void setPrintBill(Integer printBill) {
        this.printBill = printBill;
    }

    public String getWechatAccountQrcode() {
        return wechatAccountQrcode;
    }

    public void setWechatAccountQrcode(String wechatAccountQrcode) {
        this.wechatAccountQrcode = wechatAccountQrcode;
    }

    public String getWechatAccountQrcodeContent() {
        return wechatAccountQrcodeContent;
    }

    public void setWechatAccountQrcodeContent(String wechatAccountQrcodeContent) {
        this.wechatAccountQrcodeContent = wechatAccountQrcodeContent;
    }

    public String getWechatReceiptQrcode() {
        return wechatReceiptQrcode;
    }

    public void setWechatReceiptQrcode(String wechatReceiptQrcode) {
        this.wechatReceiptQrcode = wechatReceiptQrcode;
    }

    public String getWechatReceiptQrcodeContent() {
        return wechatReceiptQrcodeContent;
    }

    public void setWechatReceiptQrcodeContent(String wechatReceiptQrcodeContent) {
        this.wechatReceiptQrcodeContent = wechatReceiptQrcodeContent;
    }

    public String getAlipayAccountQrcode() {
        return alipayAccountQrcode;
    }

    public void setAlipayAccountQrcode(String alipayAccountQrcode) {
        this.alipayAccountQrcode = alipayAccountQrcode;
    }

    public String getAlipayAccountQrcodeContent() {
        return alipayAccountQrcodeContent;
    }

    public void setAlipayAccountQrcodeContent(String alipayAccountQrcodeContent) {
        this.alipayAccountQrcodeContent = alipayAccountQrcodeContent;
    }

    public String getAlipayReceiptQrcode() {
        return alipayReceiptQrcode;
    }

    public void setAlipayReceiptQrcode(String alipayReceiptQrcode) {
        this.alipayReceiptQrcode = alipayReceiptQrcode;
    }

    public String getAlipayReceiptQrcodeContent() {
        return alipayReceiptQrcodeContent;
    }

    public void setAlipayReceiptQrcodeContent(String alipayReceiptQrcodeContent) {
        this.alipayReceiptQrcodeContent = alipayReceiptQrcodeContent;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getBankAccountName() {
        return bankAccountName;
    }

    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName;
    }

    public String getBankAccountNumber() {
        return bankAccountNumber;
    }

    public void setBankAccountNumber(String bankAccountNumber) {
        this.bankAccountNumber = bankAccountNumber;
    }

    public String getAlipayAccountName() {
        return alipayAccountName;
    }

    public void setAlipayAccountName(String alipayAccountName) {
        this.alipayAccountName = alipayAccountName;
    }

    public String getWechatAccountName() {
        return wechatAccountName;
    }

    public void setWechatAccountName(String wechatAccountName) {
        this.wechatAccountName = wechatAccountName;
    }

    public String getPrintSize() {
        return printSize;
    }

    public void setPrintSize(String printSize) {
        this.printSize = printSize;
    }

    public String getBillName() {
        return billName;
    }

    public void setBillName(String billName) {
        this.billName = billName;
    }

    public String getCtNames() {
        return ctNames;
    }

    public void setCtNames(String ctNames) {
        this.ctNames = ctNames;
    }

    public String getCtIds() {
        return ctIds;
    }

    public void setCtIds(String ctIds) {
        this.ctIds = ctIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.comp_id
     *
     * @return the value of baseinfo_company.comp_id
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.comp_id
     *
     * @param compId the value for baseinfo_company.comp_id
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.comp_name
     *
     * @return the value of baseinfo_company.comp_name
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getCompName() {
        return compName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.comp_name
     *
     * @param compName the value for baseinfo_company.comp_name
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCompName(String compName) {
        this.compName = compName == null ? null : compName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.comp_short_name
     *
     * @return the value of baseinfo_company.comp_short_name
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getCompShortName() {
        return compShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.comp_short_name
     *
     * @param compShortName the value for baseinfo_company.comp_short_name
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCompShortName(String compShortName) {
        this.compShortName = compShortName == null ? null : compShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.region_id
     *
     * @return the value of baseinfo_company.region_id
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.region_id
     *
     * @param regionId the value for baseinfo_company.region_id
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.region_name
     *
     * @return the value of baseinfo_company.region_name
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.region_name
     *
     * @param regionName the value for baseinfo_company.region_name
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.area_id
     *
     * @return the value of baseinfo_company.area_id
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.area_id
     *
     * @param areaId the value for baseinfo_company.area_id
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.province
     *
     * @return the value of baseinfo_company.province
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.province
     *
     * @param province the value for baseinfo_company.province
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.city
     *
     * @return the value of baseinfo_company.city
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.city
     *
     * @param city the value for baseinfo_company.city
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.zone
     *
     * @return the value of baseinfo_company.zone
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.zone
     *
     * @param zone the value for baseinfo_company.zone
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setZone(String zone) {
        this.zone = zone == null ? null : zone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.comp_address
     *
     * @return the value of baseinfo_company.comp_address
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getCompAddress() {
        return compAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.comp_address
     *
     * @param compAddress the value for baseinfo_company.comp_address
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCompAddress(String compAddress) {
        this.compAddress = compAddress == null ? null : compAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.comp_zip
     *
     * @return the value of baseinfo_company.comp_zip
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getCompZip() {
        return compZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.comp_zip
     *
     * @param compZip the value for baseinfo_company.comp_zip
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCompZip(String compZip) {
        this.compZip = compZip == null ? null : compZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.license
     *
     * @return the value of baseinfo_company.license
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.license
     *
     * @param license the value for baseinfo_company.license
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.license_picurl
     *
     * @return the value of baseinfo_company.license_picurl
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getLicensePicurl() {
        return licensePicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.license_picurl
     *
     * @param licensePicurl the value for baseinfo_company.license_picurl
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setLicensePicurl(String licensePicurl) {
        this.licensePicurl = licensePicurl == null ? null : licensePicurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.comp_linkman
     *
     * @return the value of baseinfo_company.comp_linkman
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getCompLinkman() {
        return compLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.comp_linkman
     *
     * @param compLinkman the value for baseinfo_company.comp_linkman
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCompLinkman(String compLinkman) {
        this.compLinkman = compLinkman == null ? null : compLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.comp_linkman_tel
     *
     * @return the value of baseinfo_company.comp_linkman_tel
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getCompLinkmanTel() {
        return compLinkmanTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.comp_linkman_tel
     *
     * @param compLinkmanTel the value for baseinfo_company.comp_linkman_tel
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCompLinkmanTel(String compLinkmanTel) {
        this.compLinkmanTel = compLinkmanTel == null ? null : compLinkmanTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.comp_sort
     *
     * @return the value of baseinfo_company.comp_sort
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Integer getCompSort() {
        return compSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.comp_sort
     *
     * @param compSort the value for baseinfo_company.comp_sort
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCompSort(Integer compSort) {
        this.compSort = compSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.nature
     *
     * @return the value of baseinfo_company.nature
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Integer getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.nature
     *
     * @param nature the value for baseinfo_company.nature
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setNature(Integer nature) {
        this.nature = nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.is_platform
     *
     * @return the value of baseinfo_company.is_platform
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Integer getIsPlatform() {
        return isPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.is_platform
     *
     * @param isPlatform the value for baseinfo_company.is_platform
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setIsPlatform(Integer isPlatform) {
        this.isPlatform = isPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.is_verified
     *
     * @return the value of baseinfo_company.is_verified
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Integer getIsVerified() {
        return isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.is_verified
     *
     * @param isVerified the value for baseinfo_company.is_verified
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setIsVerified(Integer isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.verified_reason
     *
     * @return the value of baseinfo_company.verified_reason
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getVerifiedReason() {
        return verifiedReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.verified_reason
     *
     * @param verifiedReason the value for baseinfo_company.verified_reason
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setVerifiedReason(String verifiedReason) {
        this.verifiedReason = verifiedReason == null ? null : verifiedReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.verified_time
     *
     * @return the value of baseinfo_company.verified_time
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Integer getVerifiedTime() {
        return verifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.verified_time
     *
     * @param verifiedTime the value for baseinfo_company.verified_time
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setVerifiedTime(Integer verifiedTime) {
        this.verifiedTime = verifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.status
     *
     * @return the value of baseinfo_company.status
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.status
     *
     * @param status the value for baseinfo_company.status
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.admin_person_id
     *
     * @return the value of baseinfo_company.admin_person_id
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Long getAdminPersonId() {
        return adminPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.admin_person_id
     *
     * @param adminPersonId the value for baseinfo_company.admin_person_id
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setAdminPersonId(Long adminPersonId) {
        this.adminPersonId = adminPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.admin_person_name
     *
     * @return the value of baseinfo_company.admin_person_name
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getAdminPersonName() {
        return adminPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.admin_person_name
     *
     * @param adminPersonName the value for baseinfo_company.admin_person_name
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setAdminPersonName(String adminPersonName) {
        this.adminPersonName = adminPersonName == null ? null : adminPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.admin_person_mobile
     *
     * @return the value of baseinfo_company.admin_person_mobile
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getAdminPersonMobile() {
        return adminPersonMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.admin_person_mobile
     *
     * @param adminPersonMobile the value for baseinfo_company.admin_person_mobile
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setAdminPersonMobile(String adminPersonMobile) {
        this.adminPersonMobile = adminPersonMobile == null ? null : adminPersonMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.tel
     *
     * @return the value of baseinfo_company.tel
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.tel
     *
     * @param tel the value for baseinfo_company.tel
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.fax
     *
     * @return the value of baseinfo_company.fax
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.fax
     *
     * @param fax the value for baseinfo_company.fax
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.mail
     *
     * @return the value of baseinfo_company.mail
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.mail
     *
     * @param mail the value for baseinfo_company.mail
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.website
     *
     * @return the value of baseinfo_company.website
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.website
     *
     * @param website the value for baseinfo_company.website
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.memo
     *
     * @return the value of baseinfo_company.memo
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.memo
     *
     * @param memo the value for baseinfo_company.memo
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.comp_chit
     *
     * @return the value of baseinfo_company.comp_chit
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Integer getCompChit() {
        return compChit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.comp_chit
     *
     * @param compChit the value for baseinfo_company.comp_chit
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCompChit(Integer compChit) {
        this.compChit = compChit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.comp_balance
     *
     * @return the value of baseinfo_company.comp_balance
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Integer getCompBalance() {
        return compBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.comp_balance
     *
     * @param compBalance the value for baseinfo_company.comp_balance
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCompBalance(Integer compBalance) {
        this.compBalance = compBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.business_category
     *
     * @return the value of baseinfo_company.business_category
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getBusinessCategory() {
        return businessCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.business_category
     *
     * @param businessCategory the value for baseinfo_company.business_category
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setBusinessCategory(String businessCategory) {
        this.businessCategory = businessCategory == null ? null : businessCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.created_at
     *
     * @return the value of baseinfo_company.created_at
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.created_at
     *
     * @param createdAt the value for baseinfo_company.created_at
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.updated_at
     *
     * @return the value of baseinfo_company.updated_at
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.updated_at
     *
     * @param updatedAt the value for baseinfo_company.updated_at
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.created_person_id
     *
     * @return the value of baseinfo_company.created_person_id
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.created_person_id
     *
     * @param createdPersonId the value for baseinfo_company.created_person_id
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.updated_person_id
     *
     * @return the value of baseinfo_company.updated_person_id
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.updated_person_id
     *
     * @param updatedPersonId the value for baseinfo_company.updated_person_id
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.is_deleted
     *
     * @return the value of baseinfo_company.is_deleted
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.is_deleted
     *
     * @param isDeleted the value for baseinfo_company.is_deleted
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company.comp_memo
     *
     * @return the value of baseinfo_company.comp_memo
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public String getCompMemo() {
        return compMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company.comp_memo
     *
     * @param compMemo the value for baseinfo_company.comp_memo
     * @mbg.generated Thu Mar 29 10:50:33 CST 2018
     */
    public void setCompMemo(String compMemo) {
        this.compMemo = compMemo == null ? null : compMemo.trim();
    }

    public Integer getCityId() {
        return cityId;
    }

    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    public Integer getProvinceId() {
        return provinceId;
    }

    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    public Integer getExpireStatus() {
        return expireStatus;
    }

    public void setExpireStatus(Integer expireStatus) {
        this.expireStatus = expireStatus;
    }

    public void setAttributes(Map<String, String> attributes) {
        this.attributes = attributes;
    }

    public Map<String, String> getAttributesMap() {
        return this.attributes;
    }

    public String getAttributes() {
        return AttributeUtil.toString(this.attributes);
    }

    public void setAttributes(String attributes) {
        this.attributes = AttributeUtil.fromString(attributes);
    }

    public String getCompanyHead() {
        return companyHead;
    }

    public void setCompanyHead(String companyHead) {
        this.companyHead = companyHead;
    }

    public String getCompLinkTel() {
        return compLinkTel;
    }

    public void setCompLinkTel(String compLinkTel) {
        this.compLinkTel = compLinkTel;
    }

    public Integer getOnlineOrTest() {
        return onlineOrTest;
    }

    public void setOnlineOrTest(Integer onlineOrTest) {
        this.onlineOrTest = onlineOrTest;
    }
}