package com.ihappy.company.domain.dbdo;

public class BaseinfoCompanyVerifiedHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.verified_history_id
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private Integer verifiedHistoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.comp_id
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private Integer compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.nature
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private Integer nature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.comp_name
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private String compShortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.legal_man
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private String legalMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.card_front_url
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private String cardFrontUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.card_back_url
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private String cardBackUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.license
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private String license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.license_picurl
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private String licensePicurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.is_verified
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private Integer isVerified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.verified_reason
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private String verifiedReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.created_at
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.updated_at
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.created_person_id
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.updated_person_id
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_company_verified_history.is_deleted
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.verified_history_id
     *
     * @return the value of baseinfo_company_verified_history.verified_history_id
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public Integer getVerifiedHistoryId() {
        return verifiedHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.verified_history_id
     *
     * @param verifiedHistoryId the value for baseinfo_company_verified_history.verified_history_id
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setVerifiedHistoryId(Integer verifiedHistoryId) {
        this.verifiedHistoryId = verifiedHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.comp_id
     *
     * @return the value of baseinfo_company_verified_history.comp_id
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.comp_id
     *
     * @param compId the value for baseinfo_company_verified_history.comp_id
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.nature
     *
     * @return the value of baseinfo_company_verified_history.nature
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public Integer getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.nature
     *
     * @param nature the value for baseinfo_company_verified_history.nature
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setNature(Integer nature) {
        this.nature = nature;
    }

    public String getCompShortName() {
        return compShortName;
    }

    public void setCompShortName(String compShortName) {
        this.compShortName = compShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.legal_man
     *
     * @return the value of baseinfo_company_verified_history.legal_man
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public String getLegalMan() {
        return legalMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.legal_man
     *
     * @param legalMan the value for baseinfo_company_verified_history.legal_man
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setLegalMan(String legalMan) {
        this.legalMan = legalMan == null ? null : legalMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.card_front_url
     *
     * @return the value of baseinfo_company_verified_history.card_front_url
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public String getCardFrontUrl() {
        return cardFrontUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.card_front_url
     *
     * @param cardFrontUrl the value for baseinfo_company_verified_history.card_front_url
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setCardFrontUrl(String cardFrontUrl) {
        this.cardFrontUrl = cardFrontUrl == null ? null : cardFrontUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.card_back_url
     *
     * @return the value of baseinfo_company_verified_history.card_back_url
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public String getCardBackUrl() {
        return cardBackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.card_back_url
     *
     * @param cardBackUrl the value for baseinfo_company_verified_history.card_back_url
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setCardBackUrl(String cardBackUrl) {
        this.cardBackUrl = cardBackUrl == null ? null : cardBackUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.license
     *
     * @return the value of baseinfo_company_verified_history.license
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.license
     *
     * @param license the value for baseinfo_company_verified_history.license
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.license_picurl
     *
     * @return the value of baseinfo_company_verified_history.license_picurl
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public String getLicensePicurl() {
        return licensePicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.license_picurl
     *
     * @param licensePicurl the value for baseinfo_company_verified_history.license_picurl
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setLicensePicurl(String licensePicurl) {
        this.licensePicurl = licensePicurl == null ? null : licensePicurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.is_verified
     *
     * @return the value of baseinfo_company_verified_history.is_verified
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public Integer getIsVerified() {
        return isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.is_verified
     *
     * @param isVerified the value for baseinfo_company_verified_history.is_verified
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setIsVerified(Integer isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.verified_reason
     *
     * @return the value of baseinfo_company_verified_history.verified_reason
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public String getVerifiedReason() {
        return verifiedReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.verified_reason
     *
     * @param verifiedReason the value for baseinfo_company_verified_history.verified_reason
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setVerifiedReason(String verifiedReason) {
        this.verifiedReason = verifiedReason == null ? null : verifiedReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.created_at
     *
     * @return the value of baseinfo_company_verified_history.created_at
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.created_at
     *
     * @param createdAt the value for baseinfo_company_verified_history.created_at
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.updated_at
     *
     * @return the value of baseinfo_company_verified_history.updated_at
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.updated_at
     *
     * @param updatedAt the value for baseinfo_company_verified_history.updated_at
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.created_person_id
     *
     * @return the value of baseinfo_company_verified_history.created_person_id
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.created_person_id
     *
     * @param createdPersonId the value for baseinfo_company_verified_history.created_person_id
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.updated_person_id
     *
     * @return the value of baseinfo_company_verified_history.updated_person_id
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.updated_person_id
     *
     * @param updatedPersonId the value for baseinfo_company_verified_history.updated_person_id
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_company_verified_history.is_deleted
     *
     * @return the value of baseinfo_company_verified_history.is_deleted
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_company_verified_history.is_deleted
     *
     * @param isDeleted the value for baseinfo_company_verified_history.is_deleted
     *
     * @mbg.generated Wed Jun 06 17:19:43 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}