package com.ihappy.company.domain.dbdo;

/**
 * Created by sunjd on 2018/4/3.
 */
public class CommonParam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_param.id
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_param.key_name
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    private String keyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_param.key_value
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    private Long keyValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_param.key_type
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    private Byte keyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_param.created_at
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_param.updated_at
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_param.created_person_id
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_param.updated_person_id
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_param.is_deleted
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_param.id
     *
     * @return the value of common_param.id
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_param.id
     *
     * @param id the value for common_param.id
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_param.key_name
     *
     * @return the value of common_param.key_name
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_param.key_name
     *
     * @param keyName the value for common_param.key_name
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public void setKeyName(String keyName) {
        this.keyName = keyName == null ? null : keyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_param.key_value
     *
     * @return the value of common_param.key_value
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public Long getKeyValue() {
        return keyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_param.key_value
     *
     * @param keyValue the value for common_param.key_value
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public void setKeyValue(Long keyValue) {
        this.keyValue = keyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_param.key_type
     *
     * @return the value of common_param.key_type
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public Byte getKeyType() {
        return keyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_param.key_type
     *
     * @param keyType the value for common_param.key_type
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public void setKeyType(Byte keyType) {
        this.keyType = keyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_param.created_at
     *
     * @return the value of common_param.created_at
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_param.created_at
     *
     * @param createdAt the value for common_param.created_at
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_param.updated_at
     *
     * @return the value of common_param.updated_at
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_param.updated_at
     *
     * @param updatedAt the value for common_param.updated_at
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_param.created_person_id
     *
     * @return the value of common_param.created_person_id
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_param.created_person_id
     *
     * @param createdPersonId the value for common_param.created_person_id
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_param.updated_person_id
     *
     * @return the value of common_param.updated_person_id
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_param.updated_person_id
     *
     * @param updatedPersonId the value for common_param.updated_person_id
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_param.is_deleted
     *
     * @return the value of common_param.is_deleted
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_param.is_deleted
     *
     * @param isDeleted the value for common_param.is_deleted
     *
     * @mbg.generated Tue Apr 03 16:40:45 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}
