package com.ihappy.company.domain.dbdo;

public class OrderCompanyJournal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.order_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.order_no
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.pay_time
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.pay_person_login
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private String payPersonLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.pay_person_name
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private String payPersonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.pay_type
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.pay_money
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long payMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.comp_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.ct_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Integer ctId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.pay_content
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private String payContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.is_bill
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Integer isBill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.pay_title
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private String payTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.tax_no
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private String taxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.invite_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long invitePersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.invite_person_mobile
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private String invitePersonMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.service_due_time
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long serviceDueTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.memo
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.memo_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long memoPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.memo_person_name
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private String memoPersonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.register_tiem
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.register_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long registerPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.register_person_mobile
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private String registerPersonMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.created_at
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.created_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.updated_at
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.updated_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_company_journal.is_deleted
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    private Integer isDeleted;

    /**
     * 订单来源单号
     */
    private String sourceOrderNo;

    /**
     *  0:待审核  1作废 2通过
     */
    private Integer isCancel;

    /**
     * 服务开始时间
     */
    private Long serviceStartTime;

    /**
     * 审核员
     */
    private String auditorName;

    /**
     * 审核员
     */
    private Long auditorId;

    /**
     * 门店ID
     */
    private Long storeId;

    private Integer version;

    public String getAuditorName() {
        return auditorName;
    }

    public void setAuditorName(String auditorName) {
        this.auditorName = auditorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.order_id
     *
     * @return the value of order_company_journal.order_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.order_id
     *
     * @param orderId the value for order_company_journal.order_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.order_no
     *
     * @return the value of order_company_journal.order_no
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.order_no
     *
     * @param orderNo the value for order_company_journal.order_no
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.pay_time
     *
     * @return the value of order_company_journal.pay_time
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Long getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.pay_time
     *
     * @param payTime the value for order_company_journal.pay_time
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setPayTime(Long payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.pay_person_login
     *
     * @return the value of order_company_journal.pay_person_login
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public String getPayPersonLogin() {
        return payPersonLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.pay_person_login
     *
     * @param payPersonLogin the value for order_company_journal.pay_person_login
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setPayPersonLogin(String payPersonLogin) {
        this.payPersonLogin = payPersonLogin == null ? null : payPersonLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.pay_person_name
     *
     * @return the value of order_company_journal.pay_person_name
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public String getPayPersonName() {
        return payPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.pay_person_name
     *
     * @param payPersonName the value for order_company_journal.pay_person_name
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setPayPersonName(String payPersonName) {
        this.payPersonName = payPersonName == null ? null : payPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.pay_type
     *
     * @return the value of order_company_journal.pay_type
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.pay_type
     *
     * @param payType the value for order_company_journal.pay_type
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.pay_money
     *
     * @return the value of order_company_journal.pay_money
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Long getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.pay_money
     *
     * @param payMoney the value for order_company_journal.pay_money
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setPayMoney(Long payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.comp_id
     *
     * @return the value of order_company_journal.comp_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.comp_id
     *
     * @param compId the value for order_company_journal.comp_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.ct_id
     *
     * @return the value of order_company_journal.ct_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Integer getCtId() {
        return ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.ct_id
     *
     * @param ctId the value for order_company_journal.ct_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setCtId(Integer ctId) {
        this.ctId = ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.pay_content
     *
     * @return the value of order_company_journal.pay_content
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public String getPayContent() {
        return payContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.pay_content
     *
     * @param payContent the value for order_company_journal.pay_content
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setPayContent(String payContent) {
        this.payContent = payContent == null ? null : payContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.is_bill
     *
     * @return the value of order_company_journal.is_bill
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Integer getIsBill() {
        return isBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.is_bill
     *
     * @param isBill the value for order_company_journal.is_bill
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setIsBill(Integer isBill) {
        this.isBill = isBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.pay_title
     *
     * @return the value of order_company_journal.pay_title
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public String getPayTitle() {
        return payTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.pay_title
     *
     * @param payTitle the value for order_company_journal.pay_title
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setPayTitle(String payTitle) {
        this.payTitle = payTitle == null ? null : payTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.tax_no
     *
     * @return the value of order_company_journal.tax_no
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public String getTaxNo() {
        return taxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.tax_no
     *
     * @param taxNo the value for order_company_journal.tax_no
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setTaxNo(String taxNo) {
        this.taxNo = taxNo == null ? null : taxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.invite_person_id
     *
     * @return the value of order_company_journal.invite_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Long getInvitePersonId() {
        return invitePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.invite_person_id
     *
     * @param invitePersonId the value for order_company_journal.invite_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setInvitePersonId(Long invitePersonId) {
        this.invitePersonId = invitePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.invite_person_mobile
     *
     * @return the value of order_company_journal.invite_person_mobile
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public String getInvitePersonMobile() {
        return invitePersonMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.invite_person_mobile
     *
     * @param invitePersonMobile the value for order_company_journal.invite_person_mobile
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setInvitePersonMobile(String invitePersonMobile) {
        this.invitePersonMobile = invitePersonMobile == null ? null : invitePersonMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.service_due_time
     *
     * @return the value of order_company_journal.service_due_time
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Long getServiceDueTime() {
        return serviceDueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.service_due_time
     *
     * @param serviceDueTime the value for order_company_journal.service_due_time
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setServiceDueTime(Long serviceDueTime) {
        this.serviceDueTime = serviceDueTime;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Long getMemoPersonId() {
        return memoPersonId;
    }

    public void setMemoPersonId(Long memoPersonId) {
        this.memoPersonId = memoPersonId;
    }

    public String getMemoPersonName() {
        return memoPersonName;
    }

    public void setMemoPersonName(String memoPersonName) {
        this.memoPersonName = memoPersonName;
    }

    public Long getRegisterTime() {
        return registerTime;
    }

    public void setRegisterTime(Long registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.register_person_id
     *
     * @return the value of order_company_journal.register_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Long getRegisterPersonId() {
        return registerPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.register_person_id
     *
     * @param registerPersonId the value for order_company_journal.register_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setRegisterPersonId(Long registerPersonId) {
        this.registerPersonId = registerPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.register_person_mobile
     *
     * @return the value of order_company_journal.register_person_mobile
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public String getRegisterPersonMobile() {
        return registerPersonMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.register_person_mobile
     *
     * @param registerPersonMobile the value for order_company_journal.register_person_mobile
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setRegisterPersonMobile(String registerPersonMobile) {
        this.registerPersonMobile = registerPersonMobile == null ? null : registerPersonMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.created_at
     *
     * @return the value of order_company_journal.created_at
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.created_at
     *
     * @param createdAt the value for order_company_journal.created_at
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.created_person_id
     *
     * @return the value of order_company_journal.created_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.created_person_id
     *
     * @param createdPersonId the value for order_company_journal.created_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.updated_at
     *
     * @return the value of order_company_journal.updated_at
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.updated_at
     *
     * @param updatedAt the value for order_company_journal.updated_at
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.updated_person_id
     *
     * @return the value of order_company_journal.updated_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.updated_person_id
     *
     * @param updatedPersonId the value for order_company_journal.updated_person_id
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_company_journal.is_deleted
     *
     * @return the value of order_company_journal.is_deleted
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_company_journal.is_deleted
     *
     * @param isDeleted the value for order_company_journal.is_deleted
     *
     * @mbg.generated Thu Jun 28 15:13:36 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getSourceOrderNo() {
        return sourceOrderNo;
    }

    public void setSourceOrderNo(String sourceOrderNo) {
        this.sourceOrderNo = sourceOrderNo;
    }

    public Integer getIsCancel() {
        return isCancel;
    }

    public void setIsCancel(Integer isCancel) {
        this.isCancel = isCancel;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Long getServiceStartTime() {
        return serviceStartTime;
    }

    public void setServiceStartTime(Long serviceStartTime) {
        this.serviceStartTime = serviceStartTime;
    }

    public Long getAuditorId() {
        return auditorId;
    }

    public void setAuditorId(Long auditorId) {
        this.auditorId = auditorId;
    }

    public Long getStoreId() {
        return storeId;
    }

    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }
}