package com.ihappy.company.domain.dbdo;

import java.io.Serializable;

public class SysCompanyTypePrintBill implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company_type_print_bill.pb_id
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    private Long pbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company_type_print_bill.bill_type
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    private Integer billType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company_type_print_bill.bill_type_code
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    private Integer billTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company_type_print_bill.bill_type_name
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    private String billTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company_type_print_bill.ct_id
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    private Integer ctId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company_type_print_bill.created_at
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company_type_print_bill.updated_at
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company_type_print_bill.created_person_id
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company_type_print_bill.updated_person_id
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company_type_print_bill.is_deleted
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company_type_print_bill.pb_id
     *
     * @return the value of sys_company_type_print_bill.pb_id
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public Long getPbId() {
        return pbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company_type_print_bill.pb_id
     *
     * @param pbId the value for sys_company_type_print_bill.pb_id
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public void setPbId(Long pbId) {
        this.pbId = pbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company_type_print_bill.bill_type
     *
     * @return the value of sys_company_type_print_bill.bill_type
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public Integer getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company_type_print_bill.bill_type
     *
     * @param billType the value for sys_company_type_print_bill.bill_type
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public void setBillType(Integer billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company_type_print_bill.bill_type_code
     *
     * @return the value of sys_company_type_print_bill.bill_type_code
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public Integer getBillTypeCode() {
        return billTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company_type_print_bill.bill_type_code
     *
     * @param billTypeCode the value for sys_company_type_print_bill.bill_type_code
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public void setBillTypeCode(Integer billTypeCode) {
        this.billTypeCode = billTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company_type_print_bill.bill_type_name
     *
     * @return the value of sys_company_type_print_bill.bill_type_name
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public String getBillTypeName() {
        return billTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company_type_print_bill.bill_type_name
     *
     * @param billTypeName the value for sys_company_type_print_bill.bill_type_name
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public void setBillTypeName(String billTypeName) {
        this.billTypeName = billTypeName == null ? null : billTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company_type_print_bill.ct_id
     *
     * @return the value of sys_company_type_print_bill.ct_id
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public Integer getCtId() {
        return ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company_type_print_bill.ct_id
     *
     * @param ctId the value for sys_company_type_print_bill.ct_id
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public void setCtId(Integer ctId) {
        this.ctId = ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company_type_print_bill.created_at
     *
     * @return the value of sys_company_type_print_bill.created_at
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company_type_print_bill.created_at
     *
     * @param createdAt the value for sys_company_type_print_bill.created_at
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company_type_print_bill.updated_at
     *
     * @return the value of sys_company_type_print_bill.updated_at
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company_type_print_bill.updated_at
     *
     * @param updatedAt the value for sys_company_type_print_bill.updated_at
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company_type_print_bill.created_person_id
     *
     * @return the value of sys_company_type_print_bill.created_person_id
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company_type_print_bill.created_person_id
     *
     * @param createdPersonId the value for sys_company_type_print_bill.created_person_id
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company_type_print_bill.updated_person_id
     *
     * @return the value of sys_company_type_print_bill.updated_person_id
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company_type_print_bill.updated_person_id
     *
     * @param updatedPersonId the value for sys_company_type_print_bill.updated_person_id
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company_type_print_bill.is_deleted
     *
     * @return the value of sys_company_type_print_bill.is_deleted
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company_type_print_bill.is_deleted
     *
     * @param isDeleted the value for sys_company_type_print_bill.is_deleted
     *
     * @mbg.generated Mon Jun 04 16:50:28 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}