package com.ihappy.company.domain.dbdo;

public class SysGoodsCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_goods_category.gc_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    private Long gcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_goods_category.gc_name
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    private String gcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_goods_category.gc_sort
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    private Long gcSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_goods_category.parent_gc_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    private Long parentGcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_goods_category.gc_depth
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    private String gcDepth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_goods_category.indcate_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    private Long indcateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_goods_category.created_at
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_goods_category.updated_at
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_goods_category.created_person_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_goods_category.updated_person_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_goods_category.is_deleted
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_goods_category.gc_id
     *
     * @return the value of sys_goods_category.gc_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public Long getGcId() {
        return gcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_goods_category.gc_id
     *
     * @param gcId the value for sys_goods_category.gc_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public void setGcId(Long gcId) {
        this.gcId = gcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_goods_category.gc_name
     *
     * @return the value of sys_goods_category.gc_name
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public String getGcName() {
        return gcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_goods_category.gc_name
     *
     * @param gcName the value for sys_goods_category.gc_name
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public void setGcName(String gcName) {
        this.gcName = gcName == null ? null : gcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_goods_category.gc_sort
     *
     * @return the value of sys_goods_category.gc_sort
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public Long getGcSort() {
        return gcSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_goods_category.gc_sort
     *
     * @param gcSort the value for sys_goods_category.gc_sort
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public void setGcSort(Long gcSort) {
        this.gcSort = gcSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_goods_category.parent_gc_id
     *
     * @return the value of sys_goods_category.parent_gc_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public Long getParentGcId() {
        return parentGcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_goods_category.parent_gc_id
     *
     * @param parentGcId the value for sys_goods_category.parent_gc_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public void setParentGcId(Long parentGcId) {
        this.parentGcId = parentGcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_goods_category.gc_depth
     *
     * @return the value of sys_goods_category.gc_depth
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public String getGcDepth() {
        return gcDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_goods_category.gc_depth
     *
     * @param gcDepth the value for sys_goods_category.gc_depth
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public void setGcDepth(String gcDepth) {
        this.gcDepth = gcDepth == null ? null : gcDepth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_goods_category.indcate_id
     *
     * @return the value of sys_goods_category.indcate_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public Long getIndcateId() {
        return indcateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_goods_category.indcate_id
     *
     * @param indcateId the value for sys_goods_category.indcate_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public void setIndcateId(Long indcateId) {
        this.indcateId = indcateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_goods_category.created_at
     *
     * @return the value of sys_goods_category.created_at
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_goods_category.created_at
     *
     * @param createdAt the value for sys_goods_category.created_at
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_goods_category.updated_at
     *
     * @return the value of sys_goods_category.updated_at
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_goods_category.updated_at
     *
     * @param updatedAt the value for sys_goods_category.updated_at
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_goods_category.created_person_id
     *
     * @return the value of sys_goods_category.created_person_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_goods_category.created_person_id
     *
     * @param createdPersonId the value for sys_goods_category.created_person_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_goods_category.updated_person_id
     *
     * @return the value of sys_goods_category.updated_person_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_goods_category.updated_person_id
     *
     * @param updatedPersonId the value for sys_goods_category.updated_person_id
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_goods_category.is_deleted
     *
     * @return the value of sys_goods_category.is_deleted
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_goods_category.is_deleted
     *
     * @param isDeleted the value for sys_goods_category.is_deleted
     *
     * @mbg.generated Wed May 16 11:25:38 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}