package com.ihappy.store.infrastructure.repo.mybatis.mapper.weshop;

import com.ihappy.company.domain.dto.request.user.PersonGestureReqDTO;
import com.ihappy.store.domain.dbdo.weshop.PersonWeshopCollectionPurchase;

import java.util.List;

public interface PersonWeshopCollectionPurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_weshop_collection_purchase_0
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    int deleteByPrimaryKey(Long personWeshopCollectionPurchaseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_weshop_collection_purchase_0
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    int insert(PersonWeshopCollectionPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_weshop_collection_purchase_0
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    int insertSelective(PersonWeshopCollectionPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_weshop_collection_purchase_0
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    PersonWeshopCollectionPurchase selectByPrimaryKey(Long personWeshopCollectionPurchaseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_weshop_collection_purchase_0
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    int updateByPrimaryKeySelective(PersonWeshopCollectionPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_weshop_collection_purchase_0
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    int updateByPrimaryKey(PersonWeshopCollectionPurchase record);

    /**
     *   获取用户的行为记录表。
     * @param personGestureReqDTO
     * @return
     */
    List<PersonWeshopCollectionPurchase> selectPersonGestureList(PersonGestureReqDTO personGestureReqDTO);

    /**
     *   更新用户对指定店铺的收藏状态
     * @param personWeshopCollectionPurchase
     * @return
     */
    int updatePersonCollectionStatus(PersonWeshopCollectionPurchase personWeshopCollectionPurchase);
}