package com.ihappy.store.infrastructure.repo.mybatis.mapper.weshop;


import com.ihappy.store.domain.dbdo.weshop.WeshopCollectionJournal;

import java.util.Map;

public interface WeshopCollectionJournalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_collection_journal_0
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    int deleteByPrimaryKey(Long weshopCollectionJournalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_collection_journal_0
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    int insert(WeshopCollectionJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_collection_journal_0
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    int insertSelective(WeshopCollectionJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_collection_journal_0
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    WeshopCollectionJournal selectByPrimaryKey(Long weshopCollectionJournalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_collection_journal_0
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    int updateByPrimaryKeySelective(WeshopCollectionJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_collection_journal_0
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    int updateByPrimaryKey(WeshopCollectionJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_collection_journal_0
     *
     * @mbg.generated Mon May 21 16:34:31 CST 2018
     */
    int queryWeshopCollectionCountTimeRange(Map<String,Object> mapReq);
}