package com.ihappy.store.infrastructure.repo.mybatis.mapper.weshop;


import com.ihappy.store.domain.dbdo.weshop.WeshopVisit;

public interface WeshopVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_visit_0
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    int deleteByPrimaryKey(Long weshopVisitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_visit_0
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    int insert(WeshopVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_visit_0
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    int insertSelective(WeshopVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_visit_0
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    WeshopVisit selectByPrimaryKey(Long weshopVisitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_visit_0
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    int updateByPrimaryKeySelective(WeshopVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weshop_visit_0
     *
     * @mbg.generated Thu May 17 21:05:12 CST 2018
     */
    int updateByPrimaryKey(WeshopVisit record);
}