package com.ihappy.communal.common.enumtype;

import com.ihappy.company.common.constans.OptConstans;

/**
 * Created by renyueliang on 2018/3/6.
 */
public enum Action {

    ADD_CATEGORY(OptConstans.BUSS_OPERATION_TYPE_TEST_NEWCATEGORY, OptConstans.OPERATION_TYPE_TEST_ADD, "新增类目"),
    UPDATE_CATEGORY(OptConstans.BUSS_OPERATION_TYPE_TEST_UPDATECATEGORY, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改类目"),
    QUERY_CATEGORY(OptConstans.BUSS_OPERATION_TYPE_TEST_QUERYCATEGORY, OptConstans.BUSS_OPERATION_TYPE_TEST_QUERYCATEGORY, "查询类目"),
    QUERY_COMPANY_LIST(OptConstans.BUSS_QUERY_COMPANY_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询公司列表"),
    UPDATE_COMPANY_STATUS(OptConstans.BUSS_UPDATE_COMPANY_STATUS, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改公司状态"),
    UPDATE_COMPANY_PAY_REMARK(OptConstans.UPDATE_COMPANY_PAY_REMARK, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改企业支付备注"),
    QUERY_COMPANY_INFO(OptConstans.BUSS_QUERY_COMPANY_INFO, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询公司信息"),
    QUERY_COMPANY_INFO_WITHOUT_LOGIN(OptConstans.QUERY_COMPANY_INFO_WITHOUT_LOGIN, OptConstans.OPERATION_TYPE_TEST_QUERY, "无需登录查询公司信息"),
    QUERY_COMPANY_EXPIRE_INFO(OptConstans.QUERY_COMPANY_EXPIRE_INFO, OptConstans.QUERY_COMPANY_EXPIRE_INFO, "查询公司有效期"),
    QUERY_COMPANY_SERVICE_STATUS_PAGE(OptConstans.QUERY_COMPANY_SERVICE_STATUS_PAGE, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询公司到期及缴费情况分页列表"),
    UPDATE_COMPANY_INFO(OptConstans.BUSS_UPDATE_COMPANY_INFO, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改公司信息"),
    QUERY_PROVIDER_LIST(OptConstans.BUSS_QUERY_PROVIDER_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询供应商列表"),
    QUERY_COMPANY_ROLEID_LIST(OptConstans.BUSS_QUERY_COMPANY_ROLEID_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询角色列表"),
    QUERY_COMPNAY_ROLEID_LIST_COUNT(OptConstans.BUSS_QUERY_COMPANY_BRAND_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询公司角色列表角色数量"),

    UPDATE_COMPANY_BAR_CODE_CONFIG(OptConstans.UPDATE_COMPANY_BAR_CODE_CONFIG, OptConstans.UPDATE_COMPANY_BAR_CODE_CONFIG, "修改企业条码打印设置"),
    QUERY_COMPANY_BAR_CODE_CONFIG(OptConstans.QUERY_COMPANY_BAR_CODE_CONFIG, OptConstans.QUERY_COMPANY_BAR_CODE_CONFIG, "查询企业条码打印设置"),

    QUEREY_UPDATE_STATUS(OptConstans.QUEREY_UPDATE_STATUS, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询应用是否需要 app store更新或热更新"),

    ADD_COMPANY_INFO(OptConstans.BUSS_ADD_COMPANY_INFO, OptConstans.OPERATION_TYPE_TEST_UPDATE, "添加公司"),
    COMPLETION_COMPANY_INFO(OptConstans.COMPLETION_COMPANY_INFO, OptConstans.OPERATION_TYPE_TEST_UPDATE, "补全公司数据"),
    QUERY_COMPANY_INFO_LIST_BY_IDS(OptConstans.BUSS_QUERY_COMPANY_INFO_LIST_BY_IDS, OptConstans.OPERATION_TYPE_TEST_QUERY, "通过公司id列表查询公司信息列表"),
    QUERY_PROVIDER(OptConstans.BUSS_QUERY_QUERY_PROVIDER, OptConstans.OPERATION_TYPE_TEST_QUERY, "根据id查询供应商"),
    QUERY_DEF_PROVIDER(OptConstans.QUERY_DEF_PROVIDER, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询默认Partner"),
    FIND_PARTNER_STATISTICS(OptConstans.FIND_PARTNER_STATISTICS, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询Partner统计数据"),
    FIND_PARTNER_PAGE(OptConstans.FIND_PARTNER_PAGE, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询Partner分页列表"),
    FIND_PARTNER_LIST(OptConstans.FIND_PARTNER_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询Partner列表"),
    QUERY_PARTNER(OptConstans.QUERY_PARTNER, OptConstans.OPERATION_TYPE_TEST_QUERY, "根据id查询合作伙伴"),
    QUERY_CUSTOMER(OptConstans.BUSS_QUERY_CUSTOMER, OptConstans.OPERATION_TYPE_TEST_QUERY, "根据id查询客户"),
    QUERY_CUSTOMER_LIST(OptConstans.BUSS_QUERY_CUSTOMER_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询客户列表"),
    ADD_PROVIDER(OptConstans.BUSS_ADD_PROVIDER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "添加供应商"),
    UPDATE_PROVIDER(OptConstans.BUSS_UPDATE_PROVIDER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改供应商信息"),
    ADD_CUSTOMER(OptConstans.BUSS_ADD_CUSTOMER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "添加客户"),
    UPDATE_CUSTOMER(OptConstans.BUSS_UPDATE_CUSTOMER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改客户信息"),
    DEL_COMPANY_PARTNER(OptConstans.BUSS_DEL_COMPANY_PARTNER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "删除合作伙伴信息"),
    ADD_PARTNER_BY_INVATE_REGISTER(OptConstans.ADD_PARTNER_BY_INVATE_REGISTER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "邀请注册添加客户/供应商"),
    QUERY_COMPANY_BRAND_LIST(OptConstans.BUSS_QUERY_COMPANY_BRAND_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询企业品牌列表"),
    ADD_COMPANY_BRAND(OptConstans.BUSS_ADD_COMPANY_BRAND, OptConstans.OPERATION_TYPE_TEST_UPDATE, "添加品牌"),
    DEL_COMPANY_BRAND(OptConstans.BUSS_DEL_COMPANY_BRAND, OptConstans.OPERATION_TYPE_TEST_UPDATE, "删除品牌"),
    DEL_COMPANY_BRANDS(OptConstans.BUSS_DEL_COMPANY_BRANDS, OptConstans.OPERATION_TYPE_TEST_UPDATE, "批量删除品牌"),
    QUERY_COMPANY_SOTRE_LIST(OptConstans.BUSS_QUERY_COMPANY_SOTRE_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询门店列表"),
    QUERY_COMPANY_SOTRE(OptConstans.QUERY_COMPANY_SOTRE, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询门店详情"),
    QUERY_PERFORMANCE_PAGE(OptConstans.QUERY_PERFORMANCE_PAGE, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询门店业绩分页列表"),
    QUERY_PERFORMANCE(OptConstans.QUERY_PERFORMANCE, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询门店业绩"),
    QUERY_PERSON_PERFORMANCE_PAGE(OptConstans.QUERY_PERSON_PERFORMANCE_PAGE, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询门店员工业绩分页列表"),
    ADD_PERSON_PERFORMANCE(OptConstans.ADD_PERSON_PERFORMANCE, OptConstans.OPERATION_TYPE_TEST_QUERY, "添加员工业绩目标"),
    QUERY_STORE_LIST(OptConstans.QUERY_STORE_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询门店列表"),
    QUERY_STORE_PAGE(OptConstans.QUERY_STORE_PAGE, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询门店分页列表"),
    QUERY_STORE_MANAGER(OptConstans.QUERY_STORE_MANAGER, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询门店管理员列表"),
    QUERY_SALE_PERFORMANCE_BY_CONDITION(OptConstans.QUERY_SALE_PERFORMANCE_BY_CONDITION, OptConstans.OPERATION_TYPE_TEST_QUERY, "根据条件查询业绩指标"),
    FIND_STORE_LIST_BY_CONDITION(OptConstans.FIND_STORE_LIST_BY_CONDITION, OptConstans.OPERATION_TYPE_TEST_QUERY, "根据条件查询门店列表"),

    QUERY_STORE_LIST_WITH_PUBLIC_BY_COMPID_AND_STOREIDS(OptConstans.QUERY_STORE_LIST_WITH_PUBLIC_BY_COMPID_AND_STOREIDS, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询门店列表和总店"),
    QUERY_COMPANY_SOTRE_DETAIL(OptConstans.BUSS_QUERY_COMPANY_SOTRE_DETAIL, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询微商铺详情"),
    QUERY_COMPANY_SOTRE_DETAIL_WITHOUT_LOGIN(OptConstans.QUERY_COMPANY_SOTRE_DETAIL_WITHOUT_LOGIN, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询微商铺详情无需登录"),
    QUERY_WESHOP_VISIT_DETAIL_LIST(OptConstans.BUSS_QUERY_WESHOP_VISIT_DETAIL_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询微商铺访问信息详情列表"),

    UPDATE_COMPANY_SOTRE(OptConstans.BUSS_UPDATE_COMPANY_SOTRE, OptConstans.OPERATION_TYPE_TEST_UPDATE, "更新门店信息"),
    QUERY_DEF_PROVIDER_LIST(OptConstans.BUSS_QUERY_DEF_PROVIDER_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询默认供应商列表"),
    QUERY_DEF_CUSTOMER_LIST(OptConstans.BUSS_QUERY_DEF_CUSTOMER_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询默认客户列表"),
    QUERY_STORE_STOCK_LIST(OptConstans.BUSS_QUERY_STORE_STOCK_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询仓库列表"),
    ADD_STOCK(OptConstans.BUSS_ADD_STOCK, OptConstans.OPERATION_TYPE_TEST_UPDATE, "添加仓库"),
    QUERY_STOCK_LIST_BY_IDS(OptConstans.QUERY_STOCK_LIST_BY_IDS, OptConstans.OPERATION_TYPE_TEST_QUERY, "根据仓库id列表查询仓库列表"),
    QUERY_STOCK(OptConstans.BUSS_QUERY_STOCK, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询仓库"),
    UPDATE_STOCK(OptConstans.BUSS_UPDATE_STOCK, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改仓库"),
    UPDATE_STOCK_STATUS(OptConstans.BUSS_UPDATE_STOCK_STATUS, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改仓库状态"),
    GET_STOCK_MAP_BY_USER_INFO(OptConstans.GET_STOCK_MAP_BY_USER_INFO, OptConstans.OPERATION_TYPE_TEST_QUERY, "根据用户id 公司id查询 门店id-仓库列表 Map"),

    ADD_PARTNER_ARREARS_ORDER(OptConstans.BUSS_ADD_PARTNER_ARREARS_ORDER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "添加企业伙伴欠款订单"),
    UPDATE_PARTNER_LAST_CONTACT_TIME(OptConstans.BUSS_UPDATE_PARTNER_LAST_CONTACT_TIME, OptConstans.OPERATION_TYPE_TEST_UPDATE, "更新企业伙伴最近往来时间"),
    QUERY_PARTNER_LEVEL(OptConstans.QUERY_PARTNER_LEVEL, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询会员等级"),
    QUERY_PARTNER_LEVEL_LIST(OptConstans.QUERY_PARTNER_LEVEL_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询会员等级列表"),
    ADD_PARTNER_LEVEL(OptConstans.ADD_PARTNER_LEVEL, OptConstans.OPERATION_TYPE_TEST_UPDATE, "添加会员等级"),
    UPDATE_PARTNER_LEVEL(OptConstans.UPDATE_PARTNER_LEVEL, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改会员等级"),
    DEL_PARTNER_LEVEL(OptConstans.DEL_PARTNER_LEVEL, OptConstans.OPERATION_TYPE_TEST_UPDATE, "删除会员等级"),
    PARTNER_QUERY_OR_ADD(OptConstans.PARTNER_QUERY_OR_ADD, OptConstans.OPERATION_TYPE_TEST_UPDATE, "删除会员等级"),


    UPDATE_REFERENCE_COUNT(OptConstans.UPDATE_REFERENCE_COUNT, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改会员等级引用计数"),
    ADD_OR_QUERY_STOCK(OptConstans.ADD_OR_QUERY_STOCK, OptConstans.OPERATION_TYPE_TEST_UPDATE, "查询仓库，没有则添加"),
    UPDATE_STOCK_INVENTORYING(OptConstans.UPDATE_STOCK_INVENTORYING, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改仓库锁定状态"),
    CLEAR_STOCK_INVENTORYING(OptConstans.CLEAR_STOCK_INVENTORYING, OptConstans.OPERATION_TYPE_TEST_UPDATE, "清除仓库锁"),
    ADD_RETAIL_CUSTOMER(OptConstans.ADD_RETAIL_CUSTOMER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "添加零售会员"),
    UPDATE_RETAIL_CUSTOMER(OptConstans.UPDATE_RETAIL_CUSTOMER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "编辑零售会员"),
    DEL_RETAIL_CUSTOMER(OptConstans.DEL_RETAIL_CUSTOMER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "删除零售会员"),
    DISABLE_RETAIL_CUSTOMER(OptConstans.DISABLE_RETAIL_CUSTOMER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "禁用会员"),
    ENABLE_RETAIL_CUSTOMER(OptConstans.ENABLE_RETAIL_CUSTOMER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "启用会员"),
    QUERY_RETAIL_CUSTOMER(OptConstans.QUERY_RETAIL_CUSTOMER, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询零售会员"),
    QUERY_RETAIL_CUSTOMER_PAGE(OptConstans.QUERY_RETAIL_CUSTOMER_PAGE, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询零售会员分页列表"),
    UPDATE_PRINT_IP_AND_PORT(OptConstans.UPDATE_PRINT_IP_AND_PORT, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改门店打印ip和端口"),
    QUERY_PRINT_IP_AND_PORT(OptConstans.QUERY_PRINT_IP_AND_PORT, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询门店打印ip和端口"),
    SHARE_WESHOP(OptConstans.SHARE_WESHOP, OptConstans.OPERATION_TYPE_TEST_QUERY, "获取微商铺 分享 二维码 和 地址"),
    QUERY_COMPANY_TYPE(OptConstans.QUERY_COMPANY_TYPE, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询业务类型"),
    GET_STOCK_LIST_BY_STORE_ID_LIST(OptConstans.GET_STOCK_LIST_BY_STORE_ID_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "根据门店id列表 公司id 查询仓库列表"),
    GET_STOCK_LIST_BY_CONDITION(OptConstans.GET_STOCK_LIST_BY_CONDITION, OptConstans.OPERATION_TYPE_TEST_QUERY, "根据条件 查询仓库列表"),

    //企业组织架构
    QUERY_SYS_ORG_BY_ORG_ID_LIST(OptConstans.QUERY_SYS_ORG_BY_ORG_ID_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询部门信息"),
    GET_ALL_CHILD_SYS_ORG_BY_ID(OptConstans.GET_ALL_CHILD_SYS_ORG_BY_ID, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询所有子部门信息"),

    QUERY_PRDER_COMPANY_JOURNAL(OptConstans.QUERY_ORDER_COMPANY_JOURNAL, OptConstans.QUERY_ORDER_COMPANY_JOURNAL, "运营平台查询用户缴费记录"),

    //企业审核认证
    QUERY_VERIFY_COMPANY_INFO(OptConstans.QUERY_VERIFY_COMPANY_INFO, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询企业审核认证信息"),
    ADD_VERIFY_COMPANY_INFO(OptConstans.ADD_VERIFY_COMPANY_INFO, OptConstans.OPERATION_TYPE_TEST_UPDATE, "提交企业审核认证信息"),
    VERIFY_COMPANY_INFO(OptConstans.VERIFY_COMPANY_INFO, OptConstans.OPERATION_TYPE_TEST_UPDATE, "审核企业信息"),

    //微商铺信息
    UPDATE_USER_COLLECTION_STORE(OptConstans.UPDATE_USER_COLLECTION_STORE, OptConstans.OPERATION_TYPE_TEST_UPDATE, "更新用户收藏商品状态"),
    ADD_WESHOP_VISIT(OptConstans.ADD_WESHOP_VISIT, OptConstans.OPERATION_TYPE_TEST_UPDATE, "增加微商铺访问量"),
    ADD_COMPANY_STORE(OptConstans.ADD_COMPANY_STORE, OptConstans.ADD_COMPANY_STORE, " 增加企业门店"),
    UPDATE_COMPANY_STORE(OptConstans.UPDATE_COMPANY_STORE, OptConstans.UPDATE_COMPANY_STORE, " 修改企业门店"),
    DELETE_COMPANY_STORE(OptConstans.DELETE_COMPANY_STORE, OptConstans.DELETE_COMPANY_STORE, " 删除企业门店"),

    // 给所有公司生成默认信息
    GENERATE_DEFAULT_INFOMATION_FOR_ALL_COMPANY(OptConstans.GENERATE_DEFAULT_INFORMATION, OptConstans.OPERATION_TYPE_TEST_ADD, "给所有公司生成默认信息"),
    //查询系统公司职能信息
    QUERY_SYSCOMPANYLIST(OptConstans.QUERY_SYSCOMPANYFUNCLIST, OptConstans.QUERY_SYSCOMPANYFUNCLIST, "查询公司所有职能信息"),
    // 打印配置相关
    QUERY_PRINT_CONFIG(OptConstans.QUERY_PRINT_CONFIG, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询企业打印信息'"),
    UPDATE_PRINT_CONFIG(OptConstans.UPDATE_PRINT_CONFIG, OptConstans.OPERATION_TYPE_TEST_UPDATE, "更新企业打印信息"),
    QUERY_PRINT_CONFIG_LIST(OptConstans.QUERY_PRINT_CONFIG_LIST, OptConstans.OPERATION_TYPE_TEST_UPDATE, "更新企业打印信息"),

    //部门信息
    GET_SYS_ORG_INFO(OptConstans.GET_SYS_ORG_INFO, OptConstans.GET_SYS_ORG_INFO_QUERY, "获取部门信息"),

    //延长公司服务到期时间,并且生成流水
    ADD_COMPANY_EXTEND_SERVICE_JOURNAL(OptConstans.ADD_COMPANY_EXTEND_SERVICE_JOURNAL, OptConstans.OPERATION_TYPE_TEST_UPDATE, "延长公司服务到期时间,并且生成流水"),

    //延长公司服务到期时间,并且生成流水
    ADD_ORDER_COMPANY_SERVICE_JOURNAL(OptConstans.ADD_ORDER_COMPANY_SERVICE_JOURNAL, OptConstans.OPERATION_TYPE_TEST_UPDATE, "公司缴费服务到期时间,并且生成流水"),
    QUERY_ORDER_COMPANY_SERVICE_JOURNAL(OptConstans.QUERY_ORDER_COMPANY_SERVICE_JOURNAL, OptConstans.OPERATION_TYPE_TEST_UPDATE, "延长公司服务到期时间,并且生成流水"),
    UPDATE_ORDER_COMPANY_SERVICE_JOURNAL(OptConstans.UPDATE_ORDER_COMPANY_SERVICE_JOURNAL, OptConstans.OPERATION_TYPE_TEST_UPDATE, "延长公司服务到期时间,并且生成流水"),
    UPDATE_FACTORY_INFO(OptConstans.UPDATE_FACTORY_INFO, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改公司的工厂自定义属性信息"),
    QUERY_COMPANY_FACTORYINFO_LIST(OptConstans.QUERY_COMPANY_FACTORYINFO_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询工厂信息返回list"),
    QUERY_COMPANY_FACTORYINFO_OBJECT(OptConstans.QUERY_COMPANY_FACTORYINFO_OBJECT, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询工厂信息返回对象"),

    //后门
    REFRESH_PARTNER_STATICS(OptConstans.REFRESH_PARTNER_STATICS, OptConstans.OPERATION_TYPE_TEST_UPDATE, "刷新Partner 统计数据"),
    DELETE_REDIS(OptConstans.DELETE_REDIS, OptConstans.OPERATION_TYPE_TEST_UPDATE, "删除redis信息"),


    //企业角色相关
    ADD_COMPANY_ROLE(OptConstans.ADD_COMPANY_ROLE, OptConstans.OPERATION_TYPE_TEST_ADD, "添加公司角色"),
    UPDATE_COMPANY_ROLE_INFO(OptConstans.UPDATE_COMPANY_ROLE_INFO, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改公司角色"),
    UPDATE_SYS_COMPANY_ROLE_INFO(OptConstans.UPDATE_SYS_COMPANY_ROLE_INFO, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改系统公司角色"),
    DELETE_COMPANY_ROLE_INFO(OptConstans.DELETE_COMPANY_ROLE_INFO, OptConstans.OPERATION_TYPE_TEST_UPDATE, "删除公司角色"),
    DELETE_SYS_COMPANY_ROLE_INFO(OptConstans.DELETE_SYS_COMPANY_ROLE_INFO, OptConstans.OPERATION_TYPE_TEST_UPDATE, "删除公司角色"),
    QUERY_COMPANY_ROLE_INFO(OptConstans.QUERY_COMPANY_ROLE_INFO, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询公司角色详情"),
    QUERY_COMPANY_ROLE_ID_COUNT(OptConstans.QUERY_COMPANY_ROLE_ID_COUNT, OptConstans.QUERY_COMPANY_ROLE_ID_COUNT, "查询公司角色数量"),
    QUERY_COMPANY_ROLE_MENU_LIST(OptConstans.QUERY_COMPANY_ROLE_MENU_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询公司角色菜单列表"),
    QUERY_COMPANY_ROLE_TYPE_LIST(OptConstans.QUERY_COMPANY_ROLE_TYPE_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询公司角色类型列表"),
    COPY_ROLE(OptConstans.COPY_ROLE, OptConstans.OPERATION_TYPE_TEST_ADD, "复制角色"),
    QUERY_APP_ROLE_LIST_BY_DIFF_POWER(OptConstans.QUERY_APP_ROLE_LIST_BY_DIFF_POWER, OptConstans.OPERATION_TYPE_TEST_QUERY, "根据不同的权限查询角色列表"),
    //运营后台角色相关
    QUERY_ROLEID_LIST(OptConstans.QUERY_ROLE_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询运营平台角色列表"),
    QUERY_ROLE_INFO(OptConstans.QUERY_ROLE_INFO, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询运营后台角色详情"),
    UPDATE_ROLE_INFO(OptConstans.UPDATE_ROLE_INFO, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改运营后台角色信息"),
    DELETE_ROLE_INFO(OptConstans.DELETE_ROLE_INFO, OptConstans.DELETE_ROLE_INFO, "删除运营后台角色信息"),
    ADD_SYS_ROLE_INFO(OptConstans.ADD_SYS_ROLE_INFO, OptConstans.ADD_SYS_ROLE_INFO, "添加运营后台角色信息"),
    QUERY_SYS_CLIENT_LIST(OptConstans.QUEY_SYS_CLIENT_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询系统客户端列表"),
    QUERY_SYS_COMPANY_TYPE_LIST(OptConstans.QUERY_SYS_COMPANY_TYPE_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询系统公司类型列表"),
    QUERY_SYS_COMPANY_ROLE_INFO_CLIENT_TYPE_LIST(OptConstans.QUERY_SYS_COMPANY_ROLE_INFO_CLIENT_TYPE_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询系统公司角色详情应用配置类型列表"),
    QUERY_SYS_COMPANY_ROLE_ADD_CLIENT_TYPE_LIST(OptConstans.QUERY_SYS_COMPANY_ROLE_ADD_CLIENT_TYPE_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "运营后台平台设定角色配置角色添加应用配置类型列表查询"),
    QUERY_SYS_COMPANY_ROLE_ADD_CLIENT_TYPE_FUNC_LIST(OptConstans.QUERY_SYS_COMPANY_ROLE_ADD_CLIENT_TYPE_FUNC_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询运营后台平台设定角色配置角色添加应用配置类型功能列表"),

    //运营后台菜单相关
    QUERY_MENU_LIST(OptConstans.QUERY_MENU_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询菜单列表"),
    DELETE_MENU(OptConstans.DELETE_MENU, OptConstans.OPERATION_TYPE_TEST_UPDATE, "删除菜单"),
    ADD_MENU(OptConstans.ADD_MENU, OptConstans.OPERATION_TYPE_TEST_ADD, "添加菜单"),
    QUERY_MENU_INFO(OptConstans.QUERY_MENU_INFO, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询菜单详情"),
    UPDATE_MENU(OptConstans.UPDATE_MENU, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改菜单"),
    QUERY_TYPE_LIST(OptConstans.QUERY_TYPE_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询类型列表"),
    QUERY_TYPE_MENU_LIST(OptConstans.QUERY_TYPE_MENU_LIST, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询类型菜单列表"),
    QUERY_TYPE_MENU_INFO(OptConstans.QUERY_TYPE_MENU_INFO, OptConstans.OPERATION_TYPE_TEST_QUERY, "查询类型菜单详情"),
    //门店相关
    DISABLE_STORE(OptConstans.DISABLE_STORE, OptConstans.OPERATION_TYPE_TEST_UPDATE, "禁用门店"),
    ENABLE_STORE(OptConstans.ENABLE_STORE, OptConstans.OPERATION_TYPE_TEST_UPDATE, "启用门店"),
    QUERY_STORE_SERVICE_STATUS_PAGE(OptConstans.QUERY_STORE_SERVICE_STATUS_PAGE, OptConstans.OPERATION_TYPE_TEST_QUERY, "到期管理查询"),
    PASS_REVIEW_ORDER(OptConstans.PASS_REVIEW_ORDER, OptConstans.OPERATION_TYPE_TEST_UPDATE, "运营平台 审核通过"),
    UPDATE_STORE_PAY_REMARK(OptConstans.UPDATE_STORE_PAY_REMARK, OptConstans.OPERATION_TYPE_TEST_UPDATE, "修改门店支付备注"),;


    /**
     * 具体操作类型
     */
    private String operationType;

    /**
     * 基本操作类型   增删改
     */
    private String baseOperationType;

    /**
     * 操作名称
     */
    private String actionName;


    Action(String operationType, String baseOperationType, String actionName) {
        this.operationType = operationType;
        this.baseOperationType = baseOperationType;
        this.actionName = actionName;
    }


    public static Action getAction(String operationType) {
        for (Action a : Action.values()) {
            if (a.getOperationType().equals(operationType)) {
                return a;
            }
        }
        return null;
    }

    public String getActionName() {
        return actionName;
    }

    public String getOperationType() {
        return operationType;
    }

    public String getBaseOperationType() {
        return baseOperationType;
    }

}
