package com.ihappy.role.domain.dbdo.sys;

public class SysFunc {
    /**
     *
     */
    private Integer ctFuncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.cl_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private Integer clId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.ct_func_name
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private String ctFuncName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.ct_func_no
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private String ctFuncNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.ct_func_ico
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private String ctFuncIco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.ct_func_link
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private String ctFuncLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.ct_memo
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private String ctMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.ct_sort
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private Integer ctSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.parent_ct_func_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private Integer parentCtFuncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.status
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.func_type
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private Integer funcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.source_codes
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private String sourceCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.ct_depth
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private Integer ctDepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.canlist_noright
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private Integer canlistNoright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.created_at
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private Long createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.updated_at
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private Long updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.created_person_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private Long createdPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.updated_person_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private Long updatedPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_func.is_deleted
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.ct_func_id
     *
     * @return the value of sys_func.ct_func_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Integer getCtFuncId() {
        return ctFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.ct_func_id
     *
     * @param ctFuncId the value for sys_func.ct_func_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setCtFuncId(Integer ctFuncId) {
        this.ctFuncId = ctFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.cl_id
     *
     * @return the value of sys_func.cl_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Integer getClId() {
        return clId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.cl_id
     *
     * @param clId the value for sys_func.cl_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setClId(Integer clId) {
        this.clId = clId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.ct_func_name
     *
     * @return the value of sys_func.ct_func_name
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public String getCtFuncName() {
        return ctFuncName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.ct_func_name
     *
     * @param ctFuncName the value for sys_func.ct_func_name
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setCtFuncName(String ctFuncName) {
        this.ctFuncName = ctFuncName == null ? null : ctFuncName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.ct_func_no
     *
     * @return the value of sys_func.ct_func_no
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public String getCtFuncNo() {
        return ctFuncNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.ct_func_no
     *
     * @param ctFuncNo the value for sys_func.ct_func_no
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setCtFuncNo(String ctFuncNo) {
        this.ctFuncNo = ctFuncNo == null ? null : ctFuncNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.ct_func_ico
     *
     * @return the value of sys_func.ct_func_ico
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public String getCtFuncIco() {
        return ctFuncIco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.ct_func_ico
     *
     * @param ctFuncIco the value for sys_func.ct_func_ico
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setCtFuncIco(String ctFuncIco) {
        this.ctFuncIco = ctFuncIco == null ? null : ctFuncIco.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.ct_func_link
     *
     * @return the value of sys_func.ct_func_link
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public String getCtFuncLink() {
        return ctFuncLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.ct_func_link
     *
     * @param ctFuncLink the value for sys_func.ct_func_link
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setCtFuncLink(String ctFuncLink) {
        this.ctFuncLink = ctFuncLink == null ? null : ctFuncLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.ct_memo
     *
     * @return the value of sys_func.ct_memo
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public String getCtMemo() {
        return ctMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.ct_memo
     *
     * @param ctMemo the value for sys_func.ct_memo
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setCtMemo(String ctMemo) {
        this.ctMemo = ctMemo == null ? null : ctMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.ct_sort
     *
     * @return the value of sys_func.ct_sort
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Integer getCtSort() {
        return ctSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.ct_sort
     *
     * @param ctSort the value for sys_func.ct_sort
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setCtSort(Integer ctSort) {
        this.ctSort = ctSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.parent_ct_func_id
     *
     * @return the value of sys_func.parent_ct_func_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Integer getParentCtFuncId() {
        return parentCtFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.parent_ct_func_id
     *
     * @param parentCtFuncId the value for sys_func.parent_ct_func_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setParentCtFuncId(Integer parentCtFuncId) {
        this.parentCtFuncId = parentCtFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.status
     *
     * @return the value of sys_func.status
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.status
     *
     * @param status the value for sys_func.status
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.func_type
     *
     * @return the value of sys_func.func_type
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Integer getFuncType() {
        return funcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.func_type
     *
     * @param funcType the value for sys_func.func_type
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setFuncType(Integer funcType) {
        this.funcType = funcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.source_codes
     *
     * @return the value of sys_func.source_codes
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public String getSourceCodes() {
        return sourceCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.source_codes
     *
     * @param sourceCodes the value for sys_func.source_codes
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setSourceCodes(String sourceCodes) {
        this.sourceCodes = sourceCodes == null ? null : sourceCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.ct_depth
     *
     * @return the value of sys_func.ct_depth
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Integer getCtDepth() {
        return ctDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.ct_depth
     *
     * @param ctDepth the value for sys_func.ct_depth
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setCtDepth(Integer ctDepth) {
        this.ctDepth = ctDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.canlist_noright
     *
     * @return the value of sys_func.canlist_noright
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Integer getCanlistNoright() {
        return canlistNoright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.canlist_noright
     *
     * @param canlistNoright the value for sys_func.canlist_noright
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setCanlistNoright(Integer canlistNoright) {
        this.canlistNoright = canlistNoright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.created_at
     *
     * @return the value of sys_func.created_at
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.created_at
     *
     * @param createdAt the value for sys_func.created_at
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.updated_at
     *
     * @return the value of sys_func.updated_at
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.updated_at
     *
     * @param updatedAt the value for sys_func.updated_at
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.created_person_id
     *
     * @return the value of sys_func.created_person_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.created_person_id
     *
     * @param createdPersonId the value for sys_func.created_person_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.updated_person_id
     *
     * @return the value of sys_func.updated_person_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.updated_person_id
     *
     * @param updatedPersonId the value for sys_func.updated_person_id
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_func.is_deleted
     *
     * @return the value of sys_func.is_deleted
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_func.is_deleted
     *
     * @param isDeleted the value for sys_func.is_deleted
     *
     * @mbggenerated Sat Jun 16 10:08:39 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}