package com.ihappy.role.domain.dbdo.sys;

public class SysRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_id
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ct_id
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    private Integer ctId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_name
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_no
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    private String roleNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_memo
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    private String roleMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_rights
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    private String roleRights;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_sort
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    private Integer roleSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.created_at
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.updated_at
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.created_person_id
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    private Long createdPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.updated_person_id
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    private Long updatedPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.is_deleted
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_id
     *
     * @return the value of sys_role.role_id
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_id
     *
     * @param roleId the value for sys_role.role_id
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ct_id
     *
     * @return the value of sys_role.ct_id
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public Integer getCtId() {
        return ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ct_id
     *
     * @param ctId the value for sys_role.ct_id
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public void setCtId(Integer ctId) {
        this.ctId = ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_name
     *
     * @return the value of sys_role.role_name
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_name
     *
     * @param roleName the value for sys_role.role_name
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_no
     *
     * @return the value of sys_role.role_no
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public String getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_no
     *
     * @param roleNo the value for sys_role.role_no
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public void setRoleNo(String roleNo) {
        this.roleNo = roleNo == null ? null : roleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_memo
     *
     * @return the value of sys_role.role_memo
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public String getRoleMemo() {
        return roleMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_memo
     *
     * @param roleMemo the value for sys_role.role_memo
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public void setRoleMemo(String roleMemo) {
        this.roleMemo = roleMemo == null ? null : roleMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_rights
     *
     * @return the value of sys_role.role_rights
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public String getRoleRights() {
        return roleRights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_rights
     *
     * @param roleRights the value for sys_role.role_rights
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public void setRoleRights(String roleRights) {
        this.roleRights = roleRights == null ? null : roleRights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_sort
     *
     * @return the value of sys_role.role_sort
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public Integer getRoleSort() {
        return roleSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_sort
     *
     * @param roleSort the value for sys_role.role_sort
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public void setRoleSort(Integer roleSort) {
        this.roleSort = roleSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.created_at
     *
     * @return the value of sys_role.created_at
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.created_at
     *
     * @param createdAt the value for sys_role.created_at
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.updated_at
     *
     * @return the value of sys_role.updated_at
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.updated_at
     *
     * @param updatedAt the value for sys_role.updated_at
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.created_person_id
     *
     * @return the value of sys_role.created_person_id
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public Long getCreatedPersonId() {
        return createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.created_person_id
     *
     * @param createdPersonId the value for sys_role.created_person_id
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.updated_person_id
     *
     * @return the value of sys_role.updated_person_id
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public Long getUpdatedPersonId() {
        return updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.updated_person_id
     *
     * @param updatedPersonId the value for sys_role.updated_person_id
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public void setUpdatedPersonId(Long updatedPersonId) {
        this.updatedPersonId = updatedPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.is_deleted
     *
     * @return the value of sys_role.is_deleted
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.is_deleted
     *
     * @param isDeleted the value for sys_role.is_deleted
     *
     * @mbg.generated Sun Jun 17 14:14:37 CST 2018
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}